// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package pbnavitia

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PlaceCodeRequest_Type int32

const (
	PlaceCodeRequest_StopArea       PlaceCodeRequest_Type = 0
	PlaceCodeRequest_Network        PlaceCodeRequest_Type = 1
	PlaceCodeRequest_Company        PlaceCodeRequest_Type = 2
	PlaceCodeRequest_Line           PlaceCodeRequest_Type = 3
	PlaceCodeRequest_Route          PlaceCodeRequest_Type = 4
	PlaceCodeRequest_VehicleJourney PlaceCodeRequest_Type = 5
	PlaceCodeRequest_StopPoint      PlaceCodeRequest_Type = 6
	PlaceCodeRequest_Calendar       PlaceCodeRequest_Type = 7
)

var PlaceCodeRequest_Type_name = map[int32]string{
	0: "StopArea",
	1: "Network",
	2: "Company",
	3: "Line",
	4: "Route",
	5: "VehicleJourney",
	6: "StopPoint",
	7: "Calendar",
}
var PlaceCodeRequest_Type_value = map[string]int32{
	"StopArea":       0,
	"Network":        1,
	"Company":        2,
	"Line":           3,
	"Route":          4,
	"VehicleJourney": 5,
	"StopPoint":      6,
	"Calendar":       7,
}

func (x PlaceCodeRequest_Type) Enum() *PlaceCodeRequest_Type {
	p := new(PlaceCodeRequest_Type)
	*p = x
	return p
}
func (x PlaceCodeRequest_Type) String() string {
	return proto.EnumName(PlaceCodeRequest_Type_name, int32(x))
}
func (x *PlaceCodeRequest_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PlaceCodeRequest_Type_value, data, "PlaceCodeRequest_Type")
	if err != nil {
		return err
	}
	*x = PlaceCodeRequest_Type(value)
	return nil
}
func (PlaceCodeRequest_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{9, 0} }

type CalendarsRequest struct {
	StartDate        *string  `protobuf:"bytes,1,opt,name=start_date" json:"start_date,omitempty"`
	EndDate          *string  `protobuf:"bytes,2,opt,name=end_date" json:"end_date,omitempty"`
	Depth            *int32   `protobuf:"varint,3,opt,name=depth" json:"depth,omitempty"`
	StartPage        *int32   `protobuf:"varint,4,opt,name=start_page" json:"start_page,omitempty"`
	Count            *int32   `protobuf:"varint,5,opt,name=count" json:"count,omitempty"`
	Filter           *string  `protobuf:"bytes,6,opt,name=filter" json:"filter,omitempty"`
	ForbiddenUris    []string `protobuf:"bytes,7,rep,name=forbidden_uris" json:"forbidden_uris,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CalendarsRequest) Reset()                    { *m = CalendarsRequest{} }
func (m *CalendarsRequest) String() string            { return proto.CompactTextString(m) }
func (*CalendarsRequest) ProtoMessage()               {}
func (*CalendarsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *CalendarsRequest) GetStartDate() string {
	if m != nil && m.StartDate != nil {
		return *m.StartDate
	}
	return ""
}

func (m *CalendarsRequest) GetEndDate() string {
	if m != nil && m.EndDate != nil {
		return *m.EndDate
	}
	return ""
}

func (m *CalendarsRequest) GetDepth() int32 {
	if m != nil && m.Depth != nil {
		return *m.Depth
	}
	return 0
}

func (m *CalendarsRequest) GetStartPage() int32 {
	if m != nil && m.StartPage != nil {
		return *m.StartPage
	}
	return 0
}

func (m *CalendarsRequest) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *CalendarsRequest) GetFilter() string {
	if m != nil && m.Filter != nil {
		return *m.Filter
	}
	return ""
}

func (m *CalendarsRequest) GetForbiddenUris() []string {
	if m != nil {
		return m.ForbiddenUris
	}
	return nil
}

type TrafficReportsRequest struct {
	ApplicationPeriodBegin *uint64  `protobuf:"varint,8,opt,name=application_period_begin" json:"application_period_begin,omitempty"`
	ApplicationPeriodEnd   *uint64  `protobuf:"varint,9,opt,name=application_period_end" json:"application_period_end,omitempty"`
	XCurrentDatetime       *uint64  `protobuf:"varint,10,opt,name=_current_datetime" json:"_current_datetime,omitempty"`
	Depth                  *int32   `protobuf:"varint,3,opt,name=depth" json:"depth,omitempty"`
	StartPage              *int32   `protobuf:"varint,4,opt,name=start_page" json:"start_page,omitempty"`
	Count                  *int32   `protobuf:"varint,5,opt,name=count" json:"count,omitempty"`
	Filter                 *string  `protobuf:"bytes,6,opt,name=filter" json:"filter,omitempty"`
	ForbiddenUris          []string `protobuf:"bytes,7,rep,name=forbidden_uris" json:"forbidden_uris,omitempty"`
	XXX_unrecognized       []byte   `json:"-"`
}

func (m *TrafficReportsRequest) Reset()                    { *m = TrafficReportsRequest{} }
func (m *TrafficReportsRequest) String() string            { return proto.CompactTextString(m) }
func (*TrafficReportsRequest) ProtoMessage()               {}
func (*TrafficReportsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *TrafficReportsRequest) GetApplicationPeriodBegin() uint64 {
	if m != nil && m.ApplicationPeriodBegin != nil {
		return *m.ApplicationPeriodBegin
	}
	return 0
}

func (m *TrafficReportsRequest) GetApplicationPeriodEnd() uint64 {
	if m != nil && m.ApplicationPeriodEnd != nil {
		return *m.ApplicationPeriodEnd
	}
	return 0
}

func (m *TrafficReportsRequest) GetXCurrentDatetime() uint64 {
	if m != nil && m.XCurrentDatetime != nil {
		return *m.XCurrentDatetime
	}
	return 0
}

func (m *TrafficReportsRequest) GetDepth() int32 {
	if m != nil && m.Depth != nil {
		return *m.Depth
	}
	return 0
}

func (m *TrafficReportsRequest) GetStartPage() int32 {
	if m != nil && m.StartPage != nil {
		return *m.StartPage
	}
	return 0
}

func (m *TrafficReportsRequest) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *TrafficReportsRequest) GetFilter() string {
	if m != nil && m.Filter != nil {
		return *m.Filter
	}
	return ""
}

func (m *TrafficReportsRequest) GetForbiddenUris() []string {
	if m != nil {
		return m.ForbiddenUris
	}
	return nil
}

type LineReportsRequest struct {
	Depth            *int32   `protobuf:"varint,1,opt,name=depth" json:"depth,omitempty"`
	StartPage        *int32   `protobuf:"varint,2,opt,name=start_page" json:"start_page,omitempty"`
	Count            *int32   `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	Filter           *string  `protobuf:"bytes,4,opt,name=filter" json:"filter,omitempty"`
	ForbiddenUris    []string `protobuf:"bytes,5,rep,name=forbidden_uris" json:"forbidden_uris,omitempty"`
	SinceDatetime    *uint64  `protobuf:"varint,6,opt,name=since_datetime" json:"since_datetime,omitempty"`
	UntilDatetime    *uint64  `protobuf:"varint,7,opt,name=until_datetime" json:"until_datetime,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *LineReportsRequest) Reset()                    { *m = LineReportsRequest{} }
func (m *LineReportsRequest) String() string            { return proto.CompactTextString(m) }
func (*LineReportsRequest) ProtoMessage()               {}
func (*LineReportsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *LineReportsRequest) GetDepth() int32 {
	if m != nil && m.Depth != nil {
		return *m.Depth
	}
	return 0
}

func (m *LineReportsRequest) GetStartPage() int32 {
	if m != nil && m.StartPage != nil {
		return *m.StartPage
	}
	return 0
}

func (m *LineReportsRequest) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *LineReportsRequest) GetFilter() string {
	if m != nil && m.Filter != nil {
		return *m.Filter
	}
	return ""
}

func (m *LineReportsRequest) GetForbiddenUris() []string {
	if m != nil {
		return m.ForbiddenUris
	}
	return nil
}

func (m *LineReportsRequest) GetSinceDatetime() uint64 {
	if m != nil && m.SinceDatetime != nil {
		return *m.SinceDatetime
	}
	return 0
}

func (m *LineReportsRequest) GetUntilDatetime() uint64 {
	if m != nil && m.UntilDatetime != nil {
		return *m.UntilDatetime
	}
	return 0
}

type PlacesRequest struct {
	Q                *string       `protobuf:"bytes,1,req,name=q" json:"q,omitempty"`
	Types            []NavitiaType `protobuf:"varint,2,rep,name=types,enum=pbnavitia.NavitiaType" json:"types,omitempty"`
	Depth            *int32        `protobuf:"varint,3,req,name=depth" json:"depth,omitempty"`
	Count            *int32        `protobuf:"varint,4,req,name=count" json:"count,omitempty"`
	AdminUris        []string      `protobuf:"bytes,5,rep,name=admin_uris" json:"admin_uris,omitempty"`
	SearchType       *int32        `protobuf:"varint,6,opt,name=search_type" json:"search_type,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PlacesRequest) Reset()                    { *m = PlacesRequest{} }
func (m *PlacesRequest) String() string            { return proto.CompactTextString(m) }
func (*PlacesRequest) ProtoMessage()               {}
func (*PlacesRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *PlacesRequest) GetQ() string {
	if m != nil && m.Q != nil {
		return *m.Q
	}
	return ""
}

func (m *PlacesRequest) GetTypes() []NavitiaType {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *PlacesRequest) GetDepth() int32 {
	if m != nil && m.Depth != nil {
		return *m.Depth
	}
	return 0
}

func (m *PlacesRequest) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *PlacesRequest) GetAdminUris() []string {
	if m != nil {
		return m.AdminUris
	}
	return nil
}

func (m *PlacesRequest) GetSearchType() int32 {
	if m != nil && m.SearchType != nil {
		return *m.SearchType
	}
	return 0
}

type NextStopTimeRequest struct {
	DepartureFilter  *string  `protobuf:"bytes,1,req,name=departure_filter" json:"departure_filter,omitempty"`
	ArrivalFilter    *string  `protobuf:"bytes,2,req,name=arrival_filter" json:"arrival_filter,omitempty"`
	FromDatetime     *uint64  `protobuf:"varint,3,opt,name=from_datetime" json:"from_datetime,omitempty"`
	Duration         *int32   `protobuf:"varint,4,req,name=duration" json:"duration,omitempty"`
	Depth            *int32   `protobuf:"varint,5,req,name=depth" json:"depth,omitempty"`
	NbStoptimes      *int32   `protobuf:"varint,7,req,name=nb_stoptimes" json:"nb_stoptimes,omitempty"`
	InterfaceVersion *int32   `protobuf:"varint,8,opt,name=interface_version" json:"interface_version,omitempty"`
	StartPage        *int32   `protobuf:"varint,9,req,name=start_page" json:"start_page,omitempty"`
	Count            *int32   `protobuf:"varint,10,req,name=count" json:"count,omitempty"`
	MaxDateTimes     *int32   `protobuf:"varint,11,opt,name=max_date_times" json:"max_date_times,omitempty"`
	ForbiddenUri     []string `protobuf:"bytes,12,rep,name=forbidden_uri" json:"forbidden_uri,omitempty"`
	Calendar         *string  `protobuf:"bytes,13,opt,name=calendar" json:"calendar,omitempty"`
	ShowCodes        *bool    `protobuf:"varint,14,opt,name=show_codes" json:"show_codes,omitempty"`
	UntilDatetime    *uint64  `protobuf:"varint,15,opt,name=until_datetime" json:"until_datetime,omitempty"`
	XCurrentDatetime *uint64  `protobuf:"varint,16,opt,name=_current_datetime" json:"_current_datetime,omitempty"`
	RealtimeLevel    *RTLevel `protobuf:"varint,17,opt,name=realtime_level,enum=pbnavitia.RTLevel" json:"realtime_level,omitempty"`
	ItemsPerSchedule *int32   `protobuf:"varint,18,opt,name=items_per_schedule" json:"items_per_schedule,omitempty"`
	DisableGeojson   *bool    `protobuf:"varint,19,opt,name=disable_geojson" json:"disable_geojson,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *NextStopTimeRequest) Reset()                    { *m = NextStopTimeRequest{} }
func (m *NextStopTimeRequest) String() string            { return proto.CompactTextString(m) }
func (*NextStopTimeRequest) ProtoMessage()               {}
func (*NextStopTimeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *NextStopTimeRequest) GetDepartureFilter() string {
	if m != nil && m.DepartureFilter != nil {
		return *m.DepartureFilter
	}
	return ""
}

func (m *NextStopTimeRequest) GetArrivalFilter() string {
	if m != nil && m.ArrivalFilter != nil {
		return *m.ArrivalFilter
	}
	return ""
}

func (m *NextStopTimeRequest) GetFromDatetime() uint64 {
	if m != nil && m.FromDatetime != nil {
		return *m.FromDatetime
	}
	return 0
}

func (m *NextStopTimeRequest) GetDuration() int32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *NextStopTimeRequest) GetDepth() int32 {
	if m != nil && m.Depth != nil {
		return *m.Depth
	}
	return 0
}

func (m *NextStopTimeRequest) GetNbStoptimes() int32 {
	if m != nil && m.NbStoptimes != nil {
		return *m.NbStoptimes
	}
	return 0
}

func (m *NextStopTimeRequest) GetInterfaceVersion() int32 {
	if m != nil && m.InterfaceVersion != nil {
		return *m.InterfaceVersion
	}
	return 0
}

func (m *NextStopTimeRequest) GetStartPage() int32 {
	if m != nil && m.StartPage != nil {
		return *m.StartPage
	}
	return 0
}

func (m *NextStopTimeRequest) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *NextStopTimeRequest) GetMaxDateTimes() int32 {
	if m != nil && m.MaxDateTimes != nil {
		return *m.MaxDateTimes
	}
	return 0
}

func (m *NextStopTimeRequest) GetForbiddenUri() []string {
	if m != nil {
		return m.ForbiddenUri
	}
	return nil
}

func (m *NextStopTimeRequest) GetCalendar() string {
	if m != nil && m.Calendar != nil {
		return *m.Calendar
	}
	return ""
}

func (m *NextStopTimeRequest) GetShowCodes() bool {
	if m != nil && m.ShowCodes != nil {
		return *m.ShowCodes
	}
	return false
}

func (m *NextStopTimeRequest) GetUntilDatetime() uint64 {
	if m != nil && m.UntilDatetime != nil {
		return *m.UntilDatetime
	}
	return 0
}

func (m *NextStopTimeRequest) GetXCurrentDatetime() uint64 {
	if m != nil && m.XCurrentDatetime != nil {
		return *m.XCurrentDatetime
	}
	return 0
}

func (m *NextStopTimeRequest) GetRealtimeLevel() RTLevel {
	if m != nil && m.RealtimeLevel != nil {
		return *m.RealtimeLevel
	}
	return RTLevel_BASE_SCHEDULE
}

func (m *NextStopTimeRequest) GetItemsPerSchedule() int32 {
	if m != nil && m.ItemsPerSchedule != nil {
		return *m.ItemsPerSchedule
	}
	return 0
}

func (m *NextStopTimeRequest) GetDisableGeojson() bool {
	if m != nil && m.DisableGeojson != nil {
		return *m.DisableGeojson
	}
	return false
}

type StreetNetworkParams struct {
	OriginMode               *string  `protobuf:"bytes,1,opt,name=origin_mode" json:"origin_mode,omitempty"`
	DestinationMode          *string  `protobuf:"bytes,2,opt,name=destination_mode" json:"destination_mode,omitempty"`
	WalkingSpeed             *float64 `protobuf:"fixed64,3,opt,name=walking_speed" json:"walking_speed,omitempty"`
	BikeSpeed                *float64 `protobuf:"fixed64,5,opt,name=bike_speed" json:"bike_speed,omitempty"`
	CarSpeed                 *float64 `protobuf:"fixed64,7,opt,name=car_speed" json:"car_speed,omitempty"`
	BssSpeed                 *float64 `protobuf:"fixed64,9,opt,name=bss_speed" json:"bss_speed,omitempty"`
	OriginFilter             *string  `protobuf:"bytes,11,opt,name=origin_filter" json:"origin_filter,omitempty"`
	DestinationFilter        *string  `protobuf:"bytes,12,opt,name=destination_filter" json:"destination_filter,omitempty"`
	MaxWalkingDurationToPt   *int32   `protobuf:"varint,13,opt,name=max_walking_duration_to_pt" json:"max_walking_duration_to_pt,omitempty"`
	MaxBikeDurationToPt      *int32   `protobuf:"varint,14,opt,name=max_bike_duration_to_pt" json:"max_bike_duration_to_pt,omitempty"`
	MaxBssDurationToPt       *int32   `protobuf:"varint,15,opt,name=max_bss_duration_to_pt" json:"max_bss_duration_to_pt,omitempty"`
	MaxCarDurationToPt       *int32   `protobuf:"varint,16,opt,name=max_car_duration_to_pt" json:"max_car_duration_to_pt,omitempty"`
	EnableDirectPath         *bool    `protobuf:"varint,17,opt,name=enable_direct_path,def=1" json:"enable_direct_path,omitempty"`
	CarNoParkSpeed           *float64 `protobuf:"fixed64,18,opt,name=car_no_park_speed" json:"car_no_park_speed,omitempty"`
	MaxCarNoParkDurationToPt *int32   `protobuf:"varint,19,opt,name=max_car_no_park_duration_to_pt" json:"max_car_no_park_duration_to_pt,omitempty"`
	XXX_unrecognized         []byte   `json:"-"`
}

func (m *StreetNetworkParams) Reset()                    { *m = StreetNetworkParams{} }
func (m *StreetNetworkParams) String() string            { return proto.CompactTextString(m) }
func (*StreetNetworkParams) ProtoMessage()               {}
func (*StreetNetworkParams) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

const Default_StreetNetworkParams_EnableDirectPath bool = true

func (m *StreetNetworkParams) GetOriginMode() string {
	if m != nil && m.OriginMode != nil {
		return *m.OriginMode
	}
	return ""
}

func (m *StreetNetworkParams) GetDestinationMode() string {
	if m != nil && m.DestinationMode != nil {
		return *m.DestinationMode
	}
	return ""
}

func (m *StreetNetworkParams) GetWalkingSpeed() float64 {
	if m != nil && m.WalkingSpeed != nil {
		return *m.WalkingSpeed
	}
	return 0
}

func (m *StreetNetworkParams) GetBikeSpeed() float64 {
	if m != nil && m.BikeSpeed != nil {
		return *m.BikeSpeed
	}
	return 0
}

func (m *StreetNetworkParams) GetCarSpeed() float64 {
	if m != nil && m.CarSpeed != nil {
		return *m.CarSpeed
	}
	return 0
}

func (m *StreetNetworkParams) GetBssSpeed() float64 {
	if m != nil && m.BssSpeed != nil {
		return *m.BssSpeed
	}
	return 0
}

func (m *StreetNetworkParams) GetOriginFilter() string {
	if m != nil && m.OriginFilter != nil {
		return *m.OriginFilter
	}
	return ""
}

func (m *StreetNetworkParams) GetDestinationFilter() string {
	if m != nil && m.DestinationFilter != nil {
		return *m.DestinationFilter
	}
	return ""
}

func (m *StreetNetworkParams) GetMaxWalkingDurationToPt() int32 {
	if m != nil && m.MaxWalkingDurationToPt != nil {
		return *m.MaxWalkingDurationToPt
	}
	return 0
}

func (m *StreetNetworkParams) GetMaxBikeDurationToPt() int32 {
	if m != nil && m.MaxBikeDurationToPt != nil {
		return *m.MaxBikeDurationToPt
	}
	return 0
}

func (m *StreetNetworkParams) GetMaxBssDurationToPt() int32 {
	if m != nil && m.MaxBssDurationToPt != nil {
		return *m.MaxBssDurationToPt
	}
	return 0
}

func (m *StreetNetworkParams) GetMaxCarDurationToPt() int32 {
	if m != nil && m.MaxCarDurationToPt != nil {
		return *m.MaxCarDurationToPt
	}
	return 0
}

func (m *StreetNetworkParams) GetEnableDirectPath() bool {
	if m != nil && m.EnableDirectPath != nil {
		return *m.EnableDirectPath
	}
	return Default_StreetNetworkParams_EnableDirectPath
}

func (m *StreetNetworkParams) GetCarNoParkSpeed() float64 {
	if m != nil && m.CarNoParkSpeed != nil {
		return *m.CarNoParkSpeed
	}
	return 0
}

func (m *StreetNetworkParams) GetMaxCarNoParkDurationToPt() int32 {
	if m != nil && m.MaxCarNoParkDurationToPt != nil {
		return *m.MaxCarNoParkDurationToPt
	}
	return 0
}

type JourneysRequest struct {
	Origin                 []*LocationContext   `protobuf:"bytes,1,rep,name=origin" json:"origin,omitempty"`
	Destination            []*LocationContext   `protobuf:"bytes,2,rep,name=destination" json:"destination,omitempty"`
	Datetimes              []uint64             `protobuf:"varint,3,rep,name=datetimes" json:"datetimes,omitempty"`
	Clockwise              *bool                `protobuf:"varint,4,req,name=clockwise" json:"clockwise,omitempty"`
	ForbiddenUris          []string             `protobuf:"bytes,5,rep,name=forbidden_uris" json:"forbidden_uris,omitempty"`
	MaxDuration            *int32               `protobuf:"varint,6,req,name=max_duration" json:"max_duration,omitempty"`
	MaxTransfers           *int32               `protobuf:"varint,7,req,name=max_transfers" json:"max_transfers,omitempty"`
	StreetnetworkParams    *StreetNetworkParams `protobuf:"bytes,8,opt,name=streetnetwork_params" json:"streetnetwork_params,omitempty"`
	Wheelchair             *bool                `protobuf:"varint,9,opt,name=wheelchair,def=0" json:"wheelchair,omitempty"`
	ShowCodes              *bool                `protobuf:"varint,11,opt,name=show_codes" json:"show_codes,omitempty"`
	Details                *bool                `protobuf:"varint,13,opt,name=details" json:"details,omitempty"`
	RealtimeLevel          *RTLevel             `protobuf:"varint,14,opt,name=realtime_level,enum=pbnavitia.RTLevel" json:"realtime_level,omitempty"`
	MaxExtraSecondPass     *int32               `protobuf:"varint,15,opt,name=max_extra_second_pass,def=0" json:"max_extra_second_pass,omitempty"`
	WalkingTransferPenalty *int32               `protobuf:"varint,16,opt,name=walking_transfer_penalty,def=120" json:"walking_transfer_penalty,omitempty"`
	DirectPathDuration     *int32               `protobuf:"varint,17,opt,name=direct_path_duration" json:"direct_path_duration,omitempty"`
	BikeInPt               *bool                `protobuf:"varint,18,opt,name=bike_in_pt" json:"bike_in_pt,omitempty"`
	AllowedId              []string             `protobuf:"bytes,19,rep,name=allowed_id" json:"allowed_id,omitempty"`
	FreeRadiusFrom         *int32               `protobuf:"varint,20,opt,name=free_radius_from,def=0" json:"free_radius_from,omitempty"`
	FreeRadiusTo           *int32               `protobuf:"varint,21,opt,name=free_radius_to,def=0" json:"free_radius_to,omitempty"`
	XXX_unrecognized       []byte               `json:"-"`
}

func (m *JourneysRequest) Reset()                    { *m = JourneysRequest{} }
func (m *JourneysRequest) String() string            { return proto.CompactTextString(m) }
func (*JourneysRequest) ProtoMessage()               {}
func (*JourneysRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

const Default_JourneysRequest_Wheelchair bool = false
const Default_JourneysRequest_MaxExtraSecondPass int32 = 0
const Default_JourneysRequest_WalkingTransferPenalty int32 = 120
const Default_JourneysRequest_FreeRadiusFrom int32 = 0
const Default_JourneysRequest_FreeRadiusTo int32 = 0

func (m *JourneysRequest) GetOrigin() []*LocationContext {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *JourneysRequest) GetDestination() []*LocationContext {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *JourneysRequest) GetDatetimes() []uint64 {
	if m != nil {
		return m.Datetimes
	}
	return nil
}

func (m *JourneysRequest) GetClockwise() bool {
	if m != nil && m.Clockwise != nil {
		return *m.Clockwise
	}
	return false
}

func (m *JourneysRequest) GetForbiddenUris() []string {
	if m != nil {
		return m.ForbiddenUris
	}
	return nil
}

func (m *JourneysRequest) GetMaxDuration() int32 {
	if m != nil && m.MaxDuration != nil {
		return *m.MaxDuration
	}
	return 0
}

func (m *JourneysRequest) GetMaxTransfers() int32 {
	if m != nil && m.MaxTransfers != nil {
		return *m.MaxTransfers
	}
	return 0
}

func (m *JourneysRequest) GetStreetnetworkParams() *StreetNetworkParams {
	if m != nil {
		return m.StreetnetworkParams
	}
	return nil
}

func (m *JourneysRequest) GetWheelchair() bool {
	if m != nil && m.Wheelchair != nil {
		return *m.Wheelchair
	}
	return Default_JourneysRequest_Wheelchair
}

func (m *JourneysRequest) GetShowCodes() bool {
	if m != nil && m.ShowCodes != nil {
		return *m.ShowCodes
	}
	return false
}

func (m *JourneysRequest) GetDetails() bool {
	if m != nil && m.Details != nil {
		return *m.Details
	}
	return false
}

func (m *JourneysRequest) GetRealtimeLevel() RTLevel {
	if m != nil && m.RealtimeLevel != nil {
		return *m.RealtimeLevel
	}
	return RTLevel_BASE_SCHEDULE
}

func (m *JourneysRequest) GetMaxExtraSecondPass() int32 {
	if m != nil && m.MaxExtraSecondPass != nil {
		return *m.MaxExtraSecondPass
	}
	return Default_JourneysRequest_MaxExtraSecondPass
}

func (m *JourneysRequest) GetWalkingTransferPenalty() int32 {
	if m != nil && m.WalkingTransferPenalty != nil {
		return *m.WalkingTransferPenalty
	}
	return Default_JourneysRequest_WalkingTransferPenalty
}

func (m *JourneysRequest) GetDirectPathDuration() int32 {
	if m != nil && m.DirectPathDuration != nil {
		return *m.DirectPathDuration
	}
	return 0
}

func (m *JourneysRequest) GetBikeInPt() bool {
	if m != nil && m.BikeInPt != nil {
		return *m.BikeInPt
	}
	return false
}

func (m *JourneysRequest) GetAllowedId() []string {
	if m != nil {
		return m.AllowedId
	}
	return nil
}

func (m *JourneysRequest) GetFreeRadiusFrom() int32 {
	if m != nil && m.FreeRadiusFrom != nil {
		return *m.FreeRadiusFrom
	}
	return Default_JourneysRequest_FreeRadiusFrom
}

func (m *JourneysRequest) GetFreeRadiusTo() int32 {
	if m != nil && m.FreeRadiusTo != nil {
		return *m.FreeRadiusTo
	}
	return Default_JourneysRequest_FreeRadiusTo
}

type PlacesNearbyRequest struct {
	Uri              *string       `protobuf:"bytes,1,req,name=uri" json:"uri,omitempty"`
	Distance         *float64      `protobuf:"fixed64,2,req,name=distance" json:"distance,omitempty"`
	Types            []NavitiaType `protobuf:"varint,3,rep,name=types,enum=pbnavitia.NavitiaType" json:"types,omitempty"`
	Depth            *int32        `protobuf:"varint,4,req,name=depth" json:"depth,omitempty"`
	Count            *int32        `protobuf:"varint,5,req,name=count" json:"count,omitempty"`
	StartPage        *int32        `protobuf:"varint,6,req,name=start_page" json:"start_page,omitempty"`
	Filter           *string       `protobuf:"bytes,7,opt,name=filter" json:"filter,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PlacesNearbyRequest) Reset()                    { *m = PlacesNearbyRequest{} }
func (m *PlacesNearbyRequest) String() string            { return proto.CompactTextString(m) }
func (*PlacesNearbyRequest) ProtoMessage()               {}
func (*PlacesNearbyRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *PlacesNearbyRequest) GetUri() string {
	if m != nil && m.Uri != nil {
		return *m.Uri
	}
	return ""
}

func (m *PlacesNearbyRequest) GetDistance() float64 {
	if m != nil && m.Distance != nil {
		return *m.Distance
	}
	return 0
}

func (m *PlacesNearbyRequest) GetTypes() []NavitiaType {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *PlacesNearbyRequest) GetDepth() int32 {
	if m != nil && m.Depth != nil {
		return *m.Depth
	}
	return 0
}

func (m *PlacesNearbyRequest) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *PlacesNearbyRequest) GetStartPage() int32 {
	if m != nil && m.StartPage != nil {
		return *m.StartPage
	}
	return 0
}

func (m *PlacesNearbyRequest) GetFilter() string {
	if m != nil && m.Filter != nil {
		return *m.Filter
	}
	return ""
}

type PlaceUriRequest struct {
	Uri              *string `protobuf:"bytes,1,req,name=uri" json:"uri,omitempty"`
	Depth            *int32  `protobuf:"varint,2,opt,name=depth,def=1" json:"depth,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlaceUriRequest) Reset()                    { *m = PlaceUriRequest{} }
func (m *PlaceUriRequest) String() string            { return proto.CompactTextString(m) }
func (*PlaceUriRequest) ProtoMessage()               {}
func (*PlaceUriRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

const Default_PlaceUriRequest_Depth int32 = 1

func (m *PlaceUriRequest) GetUri() string {
	if m != nil && m.Uri != nil {
		return *m.Uri
	}
	return ""
}

func (m *PlaceUriRequest) GetDepth() int32 {
	if m != nil && m.Depth != nil {
		return *m.Depth
	}
	return Default_PlaceUriRequest_Depth
}

type PlaceCodeRequest struct {
	Type             *PlaceCodeRequest_Type `protobuf:"varint,1,req,name=type,enum=pbnavitia.PlaceCodeRequest_Type" json:"type,omitempty"`
	TypeCode         *string                `protobuf:"bytes,2,req,name=type_code" json:"type_code,omitempty"`
	Code             *string                `protobuf:"bytes,3,req,name=code" json:"code,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *PlaceCodeRequest) Reset()                    { *m = PlaceCodeRequest{} }
func (m *PlaceCodeRequest) String() string            { return proto.CompactTextString(m) }
func (*PlaceCodeRequest) ProtoMessage()               {}
func (*PlaceCodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *PlaceCodeRequest) GetType() PlaceCodeRequest_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return PlaceCodeRequest_StopArea
}

func (m *PlaceCodeRequest) GetTypeCode() string {
	if m != nil && m.TypeCode != nil {
		return *m.TypeCode
	}
	return ""
}

func (m *PlaceCodeRequest) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

type PTRefRequest struct {
	RequestedType    *NavitiaType `protobuf:"varint,1,req,name=requested_type,enum=pbnavitia.NavitiaType" json:"requested_type,omitempty"`
	Filter           *string      `protobuf:"bytes,2,req,name=filter" json:"filter,omitempty"`
	Depth            *int32       `protobuf:"varint,3,req,name=depth" json:"depth,omitempty"`
	StartPage        *int32       `protobuf:"varint,4,req,name=start_page" json:"start_page,omitempty"`
	Count            *int32       `protobuf:"varint,5,req,name=count" json:"count,omitempty"`
	ShowCodes        *bool        `protobuf:"varint,7,opt,name=show_codes" json:"show_codes,omitempty"`
	OdtLevel         *OdtLevel    `protobuf:"varint,8,opt,name=odt_level,enum=pbnavitia.OdtLevel" json:"odt_level,omitempty"`
	ForbiddenUri     []string     `protobuf:"bytes,6,rep,name=forbidden_uri" json:"forbidden_uri,omitempty"`
	Datetime         *uint64      `protobuf:"varint,9,opt,name=datetime" json:"datetime,omitempty"`
	SinceDatetime    *uint64      `protobuf:"varint,10,opt,name=since_datetime" json:"since_datetime,omitempty"`
	UntilDatetime    *uint64      `protobuf:"varint,11,opt,name=until_datetime" json:"until_datetime,omitempty"`
	DisableGeojson   *bool        `protobuf:"varint,12,opt,name=disable_geojson" json:"disable_geojson,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PTRefRequest) Reset()                    { *m = PTRefRequest{} }
func (m *PTRefRequest) String() string            { return proto.CompactTextString(m) }
func (*PTRefRequest) ProtoMessage()               {}
func (*PTRefRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *PTRefRequest) GetRequestedType() NavitiaType {
	if m != nil && m.RequestedType != nil {
		return *m.RequestedType
	}
	return NavitiaType_LINE
}

func (m *PTRefRequest) GetFilter() string {
	if m != nil && m.Filter != nil {
		return *m.Filter
	}
	return ""
}

func (m *PTRefRequest) GetDepth() int32 {
	if m != nil && m.Depth != nil {
		return *m.Depth
	}
	return 0
}

func (m *PTRefRequest) GetStartPage() int32 {
	if m != nil && m.StartPage != nil {
		return *m.StartPage
	}
	return 0
}

func (m *PTRefRequest) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *PTRefRequest) GetShowCodes() bool {
	if m != nil && m.ShowCodes != nil {
		return *m.ShowCodes
	}
	return false
}

func (m *PTRefRequest) GetOdtLevel() OdtLevel {
	if m != nil && m.OdtLevel != nil {
		return *m.OdtLevel
	}
	return OdtLevel_scheduled
}

func (m *PTRefRequest) GetForbiddenUri() []string {
	if m != nil {
		return m.ForbiddenUri
	}
	return nil
}

func (m *PTRefRequest) GetDatetime() uint64 {
	if m != nil && m.Datetime != nil {
		return *m.Datetime
	}
	return 0
}

func (m *PTRefRequest) GetSinceDatetime() uint64 {
	if m != nil && m.SinceDatetime != nil {
		return *m.SinceDatetime
	}
	return 0
}

func (m *PTRefRequest) GetUntilDatetime() uint64 {
	if m != nil && m.UntilDatetime != nil {
		return *m.UntilDatetime
	}
	return 0
}

func (m *PTRefRequest) GetDisableGeojson() bool {
	if m != nil && m.DisableGeojson != nil {
		return *m.DisableGeojson
	}
	return false
}

type CarCO2EmissionRequest struct {
	Origin           *LocationContext `protobuf:"bytes,1,opt,name=origin" json:"origin,omitempty"`
	Destination      *LocationContext `protobuf:"bytes,2,opt,name=destination" json:"destination,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *CarCO2EmissionRequest) Reset()                    { *m = CarCO2EmissionRequest{} }
func (m *CarCO2EmissionRequest) String() string            { return proto.CompactTextString(m) }
func (*CarCO2EmissionRequest) ProtoMessage()               {}
func (*CarCO2EmissionRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *CarCO2EmissionRequest) GetOrigin() *LocationContext {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *CarCO2EmissionRequest) GetDestination() *LocationContext {
	if m != nil {
		return m.Destination
	}
	return nil
}

type DirectPathRequest struct {
	Origin              *LocationContext     `protobuf:"bytes,1,opt,name=origin" json:"origin,omitempty"`
	Destination         *LocationContext     `protobuf:"bytes,2,opt,name=destination" json:"destination,omitempty"`
	Datetime            *uint64              `protobuf:"varint,3,opt,name=datetime" json:"datetime,omitempty"`
	Clockwise           *bool                `protobuf:"varint,4,req,name=clockwise" json:"clockwise,omitempty"`
	StreetnetworkParams *StreetNetworkParams `protobuf:"bytes,5,opt,name=streetnetwork_params" json:"streetnetwork_params,omitempty"`
	XXX_unrecognized    []byte               `json:"-"`
}

func (m *DirectPathRequest) Reset()                    { *m = DirectPathRequest{} }
func (m *DirectPathRequest) String() string            { return proto.CompactTextString(m) }
func (*DirectPathRequest) ProtoMessage()               {}
func (*DirectPathRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *DirectPathRequest) GetOrigin() *LocationContext {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *DirectPathRequest) GetDestination() *LocationContext {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *DirectPathRequest) GetDatetime() uint64 {
	if m != nil && m.Datetime != nil {
		return *m.Datetime
	}
	return 0
}

func (m *DirectPathRequest) GetClockwise() bool {
	if m != nil && m.Clockwise != nil {
		return *m.Clockwise
	}
	return false
}

func (m *DirectPathRequest) GetStreetnetworkParams() *StreetNetworkParams {
	if m != nil {
		return m.StreetnetworkParams
	}
	return nil
}

type StreetNetworkRoutingMatrixRequest struct {
	Origins          []*LocationContext `protobuf:"bytes,1,rep,name=origins" json:"origins,omitempty"`
	Destinations     []*LocationContext `protobuf:"bytes,2,rep,name=destinations" json:"destinations,omitempty"`
	Mode             *string            `protobuf:"bytes,3,opt,name=mode" json:"mode,omitempty"`
	Speed            *float32           `protobuf:"fixed32,4,opt,name=speed" json:"speed,omitempty"`
	MaxDuration      *int32             `protobuf:"varint,5,opt,name=max_duration" json:"max_duration,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *StreetNetworkRoutingMatrixRequest) Reset()         { *m = StreetNetworkRoutingMatrixRequest{} }
func (m *StreetNetworkRoutingMatrixRequest) String() string { return proto.CompactTextString(m) }
func (*StreetNetworkRoutingMatrixRequest) ProtoMessage()    {}
func (*StreetNetworkRoutingMatrixRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{13}
}

func (m *StreetNetworkRoutingMatrixRequest) GetOrigins() []*LocationContext {
	if m != nil {
		return m.Origins
	}
	return nil
}

func (m *StreetNetworkRoutingMatrixRequest) GetDestinations() []*LocationContext {
	if m != nil {
		return m.Destinations
	}
	return nil
}

func (m *StreetNetworkRoutingMatrixRequest) GetMode() string {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return ""
}

func (m *StreetNetworkRoutingMatrixRequest) GetSpeed() float32 {
	if m != nil && m.Speed != nil {
		return *m.Speed
	}
	return 0
}

func (m *StreetNetworkRoutingMatrixRequest) GetMaxDuration() int32 {
	if m != nil && m.MaxDuration != nil {
		return *m.MaxDuration
	}
	return 0
}

type MatchingRoute struct {
	LineUri            *string `protobuf:"bytes,1,opt,name=line_uri" json:"line_uri,omitempty"`
	StartStopPointUri  *string `protobuf:"bytes,2,opt,name=start_stop_point_uri" json:"start_stop_point_uri,omitempty"`
	DestinationCodeKey *string `protobuf:"bytes,3,opt,name=destination_code_key" json:"destination_code_key,omitempty"`
	DestinationCode    *string `protobuf:"bytes,4,opt,name=destination_code" json:"destination_code,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *MatchingRoute) Reset()                    { *m = MatchingRoute{} }
func (m *MatchingRoute) String() string            { return proto.CompactTextString(m) }
func (*MatchingRoute) ProtoMessage()               {}
func (*MatchingRoute) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *MatchingRoute) GetLineUri() string {
	if m != nil && m.LineUri != nil {
		return *m.LineUri
	}
	return ""
}

func (m *MatchingRoute) GetStartStopPointUri() string {
	if m != nil && m.StartStopPointUri != nil {
		return *m.StartStopPointUri
	}
	return ""
}

func (m *MatchingRoute) GetDestinationCodeKey() string {
	if m != nil && m.DestinationCodeKey != nil {
		return *m.DestinationCodeKey
	}
	return ""
}

func (m *MatchingRoute) GetDestinationCode() string {
	if m != nil && m.DestinationCode != nil {
		return *m.DestinationCode
	}
	return ""
}

type Request struct {
	RequestedApi         *API                               `protobuf:"varint,1,req,name=requested_api,enum=pbnavitia.API" json:"requested_api,omitempty"`
	Places               *PlacesRequest                     `protobuf:"bytes,2,opt,name=places" json:"places,omitempty"`
	NextStopTimes        *NextStopTimeRequest               `protobuf:"bytes,3,opt,name=next_stop_times" json:"next_stop_times,omitempty"`
	PlacesNearby         *PlacesNearbyRequest               `protobuf:"bytes,4,opt,name=places_nearby" json:"places_nearby,omitempty"`
	Journeys             *JourneysRequest                   `protobuf:"bytes,5,opt,name=journeys" json:"journeys,omitempty"`
	Ptref                *PTRefRequest                      `protobuf:"bytes,6,opt,name=ptref" json:"ptref,omitempty"`
	PlaceUri             *PlaceUriRequest                   `protobuf:"bytes,7,opt,name=place_uri" json:"place_uri,omitempty"`
	TrafficReports       *TrafficReportsRequest             `protobuf:"bytes,13,opt,name=traffic_reports" json:"traffic_reports,omitempty"`
	Calendars            *CalendarsRequest                  `protobuf:"bytes,9,opt,name=calendars" json:"calendars,omitempty"`
	PtObjects            *PtobjectRequest                   `protobuf:"bytes,10,opt,name=pt_objects" json:"pt_objects,omitempty"`
	PlaceCode            *PlaceCodeRequest                  `protobuf:"bytes,11,opt,name=place_code" json:"place_code,omitempty"`
	NearestStopPoints    *NearestStopPointsRequest          `protobuf:"bytes,14,opt,name=nearest_stop_points" json:"nearest_stop_points,omitempty"`
	XCurrentDatetime     *uint64                            `protobuf:"varint,15,opt,name=_current_datetime" json:"_current_datetime,omitempty"`
	Isochrone            *GraphicalIsochroneRequest         `protobuf:"bytes,16,opt,name=isochrone" json:"isochrone,omitempty"`
	CarCo2Emission       *CarCO2EmissionRequest             `protobuf:"bytes,17,opt,name=car_co2_emission" json:"car_co2_emission,omitempty"`
	DirectPath           *DirectPathRequest                 `protobuf:"bytes,18,opt,name=direct_path" json:"direct_path,omitempty"`
	HeatMap              *HeatMapRequest                    `protobuf:"bytes,19,opt,name=heat_map" json:"heat_map,omitempty"`
	SnRoutingMatrix      *StreetNetworkRoutingMatrixRequest `protobuf:"bytes,20,opt,name=sn_routing_matrix" json:"sn_routing_matrix,omitempty"`
	Coord                *GeographicalCoord                 `protobuf:"bytes,21,opt,name=coord" json:"coord,omitempty"`
	MatchingRoutes       *MatchingRoute                     `protobuf:"bytes,23,opt,name=matching_routes" json:"matching_routes,omitempty"`
	LineReports          *LineReportsRequest                `protobuf:"bytes,24,opt,name=line_reports" json:"line_reports,omitempty"`
	RequestId            *string                            `protobuf:"bytes,12,opt,name=request_id" json:"request_id,omitempty"`
	DisableFeedpublisher *bool                              `protobuf:"varint,22,opt,name=disable_feedpublisher" json:"disable_feedpublisher,omitempty"`
	XXX_unrecognized     []byte                             `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *Request) GetRequestedApi() API {
	if m != nil && m.RequestedApi != nil {
		return *m.RequestedApi
	}
	return API_places
}

func (m *Request) GetPlaces() *PlacesRequest {
	if m != nil {
		return m.Places
	}
	return nil
}

func (m *Request) GetNextStopTimes() *NextStopTimeRequest {
	if m != nil {
		return m.NextStopTimes
	}
	return nil
}

func (m *Request) GetPlacesNearby() *PlacesNearbyRequest {
	if m != nil {
		return m.PlacesNearby
	}
	return nil
}

func (m *Request) GetJourneys() *JourneysRequest {
	if m != nil {
		return m.Journeys
	}
	return nil
}

func (m *Request) GetPtref() *PTRefRequest {
	if m != nil {
		return m.Ptref
	}
	return nil
}

func (m *Request) GetPlaceUri() *PlaceUriRequest {
	if m != nil {
		return m.PlaceUri
	}
	return nil
}

func (m *Request) GetTrafficReports() *TrafficReportsRequest {
	if m != nil {
		return m.TrafficReports
	}
	return nil
}

func (m *Request) GetCalendars() *CalendarsRequest {
	if m != nil {
		return m.Calendars
	}
	return nil
}

func (m *Request) GetPtObjects() *PtobjectRequest {
	if m != nil {
		return m.PtObjects
	}
	return nil
}

func (m *Request) GetPlaceCode() *PlaceCodeRequest {
	if m != nil {
		return m.PlaceCode
	}
	return nil
}

func (m *Request) GetNearestStopPoints() *NearestStopPointsRequest {
	if m != nil {
		return m.NearestStopPoints
	}
	return nil
}

func (m *Request) GetXCurrentDatetime() uint64 {
	if m != nil && m.XCurrentDatetime != nil {
		return *m.XCurrentDatetime
	}
	return 0
}

func (m *Request) GetIsochrone() *GraphicalIsochroneRequest {
	if m != nil {
		return m.Isochrone
	}
	return nil
}

func (m *Request) GetCarCo2Emission() *CarCO2EmissionRequest {
	if m != nil {
		return m.CarCo2Emission
	}
	return nil
}

func (m *Request) GetDirectPath() *DirectPathRequest {
	if m != nil {
		return m.DirectPath
	}
	return nil
}

func (m *Request) GetHeatMap() *HeatMapRequest {
	if m != nil {
		return m.HeatMap
	}
	return nil
}

func (m *Request) GetSnRoutingMatrix() *StreetNetworkRoutingMatrixRequest {
	if m != nil {
		return m.SnRoutingMatrix
	}
	return nil
}

func (m *Request) GetCoord() *GeographicalCoord {
	if m != nil {
		return m.Coord
	}
	return nil
}

func (m *Request) GetMatchingRoutes() *MatchingRoute {
	if m != nil {
		return m.MatchingRoutes
	}
	return nil
}

func (m *Request) GetLineReports() *LineReportsRequest {
	if m != nil {
		return m.LineReports
	}
	return nil
}

func (m *Request) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *Request) GetDisableFeedpublisher() bool {
	if m != nil && m.DisableFeedpublisher != nil {
		return *m.DisableFeedpublisher
	}
	return false
}

type NearestStopPointsRequest struct {
	Place            *string  `protobuf:"bytes,1,opt,name=place" json:"place,omitempty"`
	Mode             *string  `protobuf:"bytes,2,opt,name=mode" json:"mode,omitempty"`
	WalkingSpeed     *float64 `protobuf:"fixed64,3,opt,name=walking_speed" json:"walking_speed,omitempty"`
	BikeSpeed        *float64 `protobuf:"fixed64,4,opt,name=bike_speed" json:"bike_speed,omitempty"`
	CarSpeed         *float64 `protobuf:"fixed64,5,opt,name=car_speed" json:"car_speed,omitempty"`
	BssSpeed         *float64 `protobuf:"fixed64,6,opt,name=bss_speed" json:"bss_speed,omitempty"`
	Filter           *string  `protobuf:"bytes,7,opt,name=filter" json:"filter,omitempty"`
	MaxDuration      *int32   `protobuf:"varint,8,opt,name=max_duration" json:"max_duration,omitempty"`
	Reverse          *bool    `protobuf:"varint,9,opt,name=reverse" json:"reverse,omitempty"`
	CarNoParkSpeed   *float64 `protobuf:"fixed64,10,opt,name=car_no_park_speed" json:"car_no_park_speed,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *NearestStopPointsRequest) Reset()                    { *m = NearestStopPointsRequest{} }
func (m *NearestStopPointsRequest) String() string            { return proto.CompactTextString(m) }
func (*NearestStopPointsRequest) ProtoMessage()               {}
func (*NearestStopPointsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *NearestStopPointsRequest) GetPlace() string {
	if m != nil && m.Place != nil {
		return *m.Place
	}
	return ""
}

func (m *NearestStopPointsRequest) GetMode() string {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return ""
}

func (m *NearestStopPointsRequest) GetWalkingSpeed() float64 {
	if m != nil && m.WalkingSpeed != nil {
		return *m.WalkingSpeed
	}
	return 0
}

func (m *NearestStopPointsRequest) GetBikeSpeed() float64 {
	if m != nil && m.BikeSpeed != nil {
		return *m.BikeSpeed
	}
	return 0
}

func (m *NearestStopPointsRequest) GetCarSpeed() float64 {
	if m != nil && m.CarSpeed != nil {
		return *m.CarSpeed
	}
	return 0
}

func (m *NearestStopPointsRequest) GetBssSpeed() float64 {
	if m != nil && m.BssSpeed != nil {
		return *m.BssSpeed
	}
	return 0
}

func (m *NearestStopPointsRequest) GetFilter() string {
	if m != nil && m.Filter != nil {
		return *m.Filter
	}
	return ""
}

func (m *NearestStopPointsRequest) GetMaxDuration() int32 {
	if m != nil && m.MaxDuration != nil {
		return *m.MaxDuration
	}
	return 0
}

func (m *NearestStopPointsRequest) GetReverse() bool {
	if m != nil && m.Reverse != nil {
		return *m.Reverse
	}
	return false
}

func (m *NearestStopPointsRequest) GetCarNoParkSpeed() float64 {
	if m != nil && m.CarNoParkSpeed != nil {
		return *m.CarNoParkSpeed
	}
	return 0
}

type GraphicalIsochroneRequest struct {
	JourneysRequest  *JourneysRequest `protobuf:"bytes,1,opt,name=journeys_request" json:"journeys_request,omitempty"`
	BoundaryDuration []int32          `protobuf:"varint,2,rep,name=boundary_duration" json:"boundary_duration,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *GraphicalIsochroneRequest) Reset()                    { *m = GraphicalIsochroneRequest{} }
func (m *GraphicalIsochroneRequest) String() string            { return proto.CompactTextString(m) }
func (*GraphicalIsochroneRequest) ProtoMessage()               {}
func (*GraphicalIsochroneRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *GraphicalIsochroneRequest) GetJourneysRequest() *JourneysRequest {
	if m != nil {
		return m.JourneysRequest
	}
	return nil
}

func (m *GraphicalIsochroneRequest) GetBoundaryDuration() []int32 {
	if m != nil {
		return m.BoundaryDuration
	}
	return nil
}

type HeatMapRequest struct {
	JourneysRequest  *JourneysRequest `protobuf:"bytes,1,opt,name=journeys_request" json:"journeys_request,omitempty"`
	Resolution       *int32           `protobuf:"varint,2,opt,name=resolution" json:"resolution,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *HeatMapRequest) Reset()                    { *m = HeatMapRequest{} }
func (m *HeatMapRequest) String() string            { return proto.CompactTextString(m) }
func (*HeatMapRequest) ProtoMessage()               {}
func (*HeatMapRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *HeatMapRequest) GetJourneysRequest() *JourneysRequest {
	if m != nil {
		return m.JourneysRequest
	}
	return nil
}

func (m *HeatMapRequest) GetResolution() int32 {
	if m != nil && m.Resolution != nil {
		return *m.Resolution
	}
	return 0
}

type PtobjectRequest struct {
	Q                *string       `protobuf:"bytes,1,req,name=q" json:"q,omitempty"`
	Types            []NavitiaType `protobuf:"varint,2,rep,name=types,enum=pbnavitia.NavitiaType" json:"types,omitempty"`
	Depth            *int32        `protobuf:"varint,3,req,name=depth" json:"depth,omitempty"`
	Count            *int32        `protobuf:"varint,4,req,name=count" json:"count,omitempty"`
	AdminUris        []string      `protobuf:"bytes,5,rep,name=admin_uris" json:"admin_uris,omitempty"`
	SearchType       *int32        `protobuf:"varint,6,opt,name=search_type" json:"search_type,omitempty"`
	DisableGeojson   *bool         `protobuf:"varint,7,opt,name=disable_geojson" json:"disable_geojson,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PtobjectRequest) Reset()                    { *m = PtobjectRequest{} }
func (m *PtobjectRequest) String() string            { return proto.CompactTextString(m) }
func (*PtobjectRequest) ProtoMessage()               {}
func (*PtobjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *PtobjectRequest) GetQ() string {
	if m != nil && m.Q != nil {
		return *m.Q
	}
	return ""
}

func (m *PtobjectRequest) GetTypes() []NavitiaType {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *PtobjectRequest) GetDepth() int32 {
	if m != nil && m.Depth != nil {
		return *m.Depth
	}
	return 0
}

func (m *PtobjectRequest) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *PtobjectRequest) GetAdminUris() []string {
	if m != nil {
		return m.AdminUris
	}
	return nil
}

func (m *PtobjectRequest) GetSearchType() int32 {
	if m != nil && m.SearchType != nil {
		return *m.SearchType
	}
	return 0
}

func (m *PtobjectRequest) GetDisableGeojson() bool {
	if m != nil && m.DisableGeojson != nil {
		return *m.DisableGeojson
	}
	return false
}

func init() {
	proto.RegisterType((*CalendarsRequest)(nil), "pbnavitia.CalendarsRequest")
	proto.RegisterType((*TrafficReportsRequest)(nil), "pbnavitia.TrafficReportsRequest")
	proto.RegisterType((*LineReportsRequest)(nil), "pbnavitia.LineReportsRequest")
	proto.RegisterType((*PlacesRequest)(nil), "pbnavitia.PlacesRequest")
	proto.RegisterType((*NextStopTimeRequest)(nil), "pbnavitia.NextStopTimeRequest")
	proto.RegisterType((*StreetNetworkParams)(nil), "pbnavitia.StreetNetworkParams")
	proto.RegisterType((*JourneysRequest)(nil), "pbnavitia.JourneysRequest")
	proto.RegisterType((*PlacesNearbyRequest)(nil), "pbnavitia.PlacesNearbyRequest")
	proto.RegisterType((*PlaceUriRequest)(nil), "pbnavitia.PlaceUriRequest")
	proto.RegisterType((*PlaceCodeRequest)(nil), "pbnavitia.PlaceCodeRequest")
	proto.RegisterType((*PTRefRequest)(nil), "pbnavitia.PTRefRequest")
	proto.RegisterType((*CarCO2EmissionRequest)(nil), "pbnavitia.CarCO2EmissionRequest")
	proto.RegisterType((*DirectPathRequest)(nil), "pbnavitia.DirectPathRequest")
	proto.RegisterType((*StreetNetworkRoutingMatrixRequest)(nil), "pbnavitia.StreetNetworkRoutingMatrixRequest")
	proto.RegisterType((*MatchingRoute)(nil), "pbnavitia.MatchingRoute")
	proto.RegisterType((*Request)(nil), "pbnavitia.Request")
	proto.RegisterType((*NearestStopPointsRequest)(nil), "pbnavitia.NearestStopPointsRequest")
	proto.RegisterType((*GraphicalIsochroneRequest)(nil), "pbnavitia.GraphicalIsochroneRequest")
	proto.RegisterType((*HeatMapRequest)(nil), "pbnavitia.HeatMapRequest")
	proto.RegisterType((*PtobjectRequest)(nil), "pbnavitia.PtobjectRequest")
	proto.RegisterEnum("pbnavitia.PlaceCodeRequest_Type", PlaceCodeRequest_Type_name, PlaceCodeRequest_Type_value)
}

func init() { proto.RegisterFile("request.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1961 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xcd, 0x92, 0x1b, 0x49,
	0x11, 0xa6, 0x25, 0xf5, 0x48, 0x4a, 0xfd, 0xf7, 0x78, 0xc6, 0x3d, 0x5e, 0xaf, 0x11, 0x02, 0x3b,
	0x14, 0xbb, 0xcb, 0xac, 0x2d, 0x20, 0x36, 0x70, 0x70, 0x60, 0x63, 0x20, 0xcc, 0x12, 0xb6, 0x77,
	0x62, 0x76, 0xe0, 0xc0, 0xa5, 0xa2, 0xd4, 0x9d, 0x1a, 0x95, 0xa7, 0xd5, 0xd5, 0x5b, 0x55, 0xf2,
	0xcc, 0xbc, 0x01, 0x67, 0xee, 0x70, 0xe1, 0xce, 0x81, 0x08, 0x6e, 0x3c, 0x01, 0x07, 0x2e, 0x9c,
	0xe0, 0xc0, 0xb3, 0x10, 0x95, 0xdd, 0x2d, 0xb5, 0x5a, 0x12, 0x78, 0x89, 0x80, 0x3d, 0x29, 0x3a,
	0xeb, 0x2f, 0x7f, 0xbe, 0xfc, 0x32, 0x53, 0xd0, 0x51, 0xf8, 0xe5, 0x12, 0xb5, 0x39, 0x4d, 0x94,
	0x34, 0xd2, 0x6b, 0x26, 0xd3, 0x98, 0xbf, 0x15, 0x46, 0xf0, 0x07, 0x60, 0xee, 0x12, 0x4c, 0xc5,
	0xa3, 0xdf, 0x38, 0xd0, 0x3f, 0xe3, 0x11, 0xc6, 0x21, 0x57, 0xfa, 0x22, 0x3d, 0xe1, 0x79, 0x00,
	0xda, 0x70, 0x65, 0x58, 0xc8, 0x0d, 0xfa, 0xce, 0xd0, 0x19, 0x37, 0xbd, 0x3e, 0x34, 0x30, 0x0e,
	0x53, 0x49, 0x85, 0x24, 0x1d, 0x70, 0x43, 0x4c, 0xcc, 0xdc, 0xaf, 0x0e, 0x9d, 0xb1, 0xbb, 0x3e,
	0x94, 0xf0, 0x2b, 0xf4, 0x6b, 0x24, 0xeb, 0x80, 0x1b, 0xc8, 0x65, 0x6c, 0x7c, 0x97, 0x3e, 0xbb,
	0x70, 0x30, 0x13, 0x91, 0x41, 0xe5, 0x1f, 0xd0, 0x0d, 0xc7, 0xd0, 0x9d, 0x49, 0x35, 0x15, 0x61,
	0x88, 0x31, 0x5b, 0x2a, 0xa1, 0xfd, 0xfa, 0xb0, 0x3a, 0x6e, 0x8e, 0xfe, 0xea, 0xc0, 0xd1, 0xa5,
	0xe2, 0xb3, 0x99, 0x08, 0x2e, 0x30, 0x91, 0xca, 0xac, 0x34, 0x1b, 0x82, 0xcf, 0x93, 0x24, 0x12,
	0x01, 0x37, 0x42, 0xc6, 0x2c, 0x41, 0x25, 0x64, 0xc8, 0xa6, 0x78, 0x25, 0x62, 0xbf, 0x31, 0x74,
	0xc6, 0x35, 0xef, 0x11, 0x1c, 0xef, 0xd8, 0x81, 0x71, 0xe8, 0x37, 0x69, 0xfd, 0x04, 0x06, 0x2c,
	0x58, 0x2a, 0x85, 0x71, 0x6a, 0x9e, 0x11, 0x0b, 0xf4, 0x81, 0x96, 0xfe, 0x77, 0x06, 0xfd, 0xce,
	0x01, 0xef, 0xa5, 0x88, 0xb1, 0x64, 0xcd, 0xea, 0x41, 0x67, 0xc7, 0x83, 0x95, 0xcd, 0x07, 0xab,
	0xa5, 0x07, 0x6b, 0x7b, 0x1e, 0x74, 0xed, 0x83, 0x56, 0xae, 0x45, 0x1c, 0xe0, 0xda, 0xc4, 0x03,
	0x32, 0xf1, 0x18, 0xba, 0xcb, 0xd8, 0x88, 0x68, 0x2d, 0xaf, 0x5b, 0xf9, 0xe8, 0xd7, 0x0e, 0x74,
	0xce, 0x23, 0x1e, 0xe0, 0x4a, 0xb7, 0x26, 0x38, 0x5f, 0xfa, 0xce, 0xb0, 0x32, 0x6e, 0x7a, 0x8f,
	0xc1, 0xb5, 0x88, 0xd1, 0x7e, 0x65, 0x58, 0x1d, 0x77, 0x27, 0xc7, 0xa7, 0x2b, 0x28, 0x9d, 0xbe,
	0x4e, 0x7f, 0x2f, 0xef, 0x12, 0x2c, 0xba, 0xaf, 0x52, 0xd4, 0xbc, 0x46, 0x9f, 0x1e, 0x00, 0x0f,
	0x17, 0x62, 0x43, 0xcb, 0x43, 0x68, 0x69, 0xe4, 0x2a, 0x98, 0x33, 0x7b, 0x3f, 0xa9, 0xe8, 0x8e,
	0xfe, 0x5c, 0x85, 0xc3, 0xd7, 0x78, 0x6b, 0xbe, 0x30, 0x32, 0xb9, 0x14, 0x0b, 0xcc, 0x15, 0xf2,
	0xa1, 0x1f, 0x62, 0xc2, 0x95, 0x59, 0x2a, 0x64, 0x99, 0x13, 0x52, 0xfd, 0x8e, 0xa1, 0xcb, 0x95,
	0x12, 0x6f, 0x79, 0x94, 0xcb, 0x2b, 0x24, 0x3f, 0x82, 0xce, 0x4c, 0xc9, 0xc5, 0xda, 0xd6, 0x2a,
	0xf9, 0xa0, 0x0f, 0x8d, 0x70, 0xa9, 0x08, 0x1e, 0x99, 0x6e, 0x2b, 0xcd, 0x5d, 0xfa, 0xbc, 0x07,
	0xed, 0x78, 0xca, 0xb4, 0x91, 0x89, 0x3d, 0x65, 0x63, 0x68, 0xa5, 0x27, 0x30, 0x10, 0xb1, 0x41,
	0x35, 0xe3, 0x01, 0xb2, 0xb7, 0xa8, 0xb4, 0x3d, 0xdf, 0xd8, 0x11, 0xb8, 0xe6, 0xa6, 0xf9, 0x40,
	0x9f, 0xc7, 0xd0, 0x5d, 0xf0, 0x5b, 0x52, 0x85, 0xa5, 0xb7, 0xb6, 0xe8, 0xa8, 0xd5, 0xb1, 0x18,
	0x40, 0xbf, 0x4d, 0x9e, 0xe9, 0x43, 0x23, 0xc8, 0xb2, 0xd2, 0xef, 0x50, 0xa4, 0xed, 0x1b, 0x73,
	0x79, 0xc3, 0x02, 0x19, 0xa2, 0xf6, 0xbb, 0x43, 0x67, 0xdc, 0xd8, 0x11, 0xcd, 0xde, 0x7e, 0x8c,
	0xf7, 0x69, 0xe9, 0x03, 0xe8, 0x2a, 0xe4, 0x91, 0x95, 0xb0, 0x08, 0xdf, 0x62, 0xe4, 0x0f, 0x86,
	0xce, 0xb8, 0x3b, 0xf1, 0x0a, 0x41, 0xbd, 0xb8, 0x7c, 0x69, 0x57, 0xbc, 0x07, 0xe0, 0x09, 0x83,
	0x0b, 0x6d, 0x93, 0x88, 0xe9, 0x60, 0x8e, 0xe1, 0x32, 0x42, 0xdf, 0x23, 0xbd, 0xef, 0x43, 0x2f,
	0x14, 0x9a, 0x4f, 0x23, 0x64, 0x57, 0x28, 0xdf, 0x68, 0x19, 0xfb, 0x87, 0x56, 0xa7, 0xd1, 0x1f,
	0xab, 0x70, 0xf8, 0x85, 0x51, 0x88, 0xe6, 0x35, 0x9a, 0x1b, 0xa9, 0xae, 0xcf, 0xb9, 0xe2, 0x0b,
	0x6d, 0x63, 0x2d, 0x95, 0xb8, 0x12, 0x31, 0x5b, 0xc8, 0x30, 0x27, 0x15, 0x8a, 0xa9, 0x36, 0x22,
	0x4e, 0x93, 0x95, 0x56, 0x52, 0x72, 0x39, 0x82, 0xce, 0x0d, 0x8f, 0xae, 0x45, 0x7c, 0xc5, 0x74,
	0x82, 0x18, 0x52, 0xec, 0x1c, 0xeb, 0x85, 0xa9, 0xb8, 0xc6, 0x4c, 0xe6, 0x92, 0x6c, 0x00, 0xcd,
	0x80, 0xab, 0x4c, 0x54, 0xcf, 0x45, 0x53, 0xad, 0x33, 0x51, 0x93, 0x44, 0x47, 0xd0, 0xc9, 0xde,
	0xcf, 0x30, 0xd2, 0xa2, 0x77, 0x1e, 0x80, 0x57, 0xd4, 0x20, 0x5b, 0x6b, 0xd3, 0xda, 0x08, 0x1e,
	0xd8, 0x98, 0xe5, 0x7a, 0xe4, 0xa0, 0x61, 0x46, 0xb2, 0xc4, 0x50, 0x58, 0x5c, 0xef, 0x9b, 0x70,
	0xdf, 0xee, 0x21, 0xa5, 0x4a, 0x1b, 0xba, 0xb4, 0xe1, 0x11, 0x1c, 0xd3, 0x06, 0xad, 0xcb, 0xeb,
	0xbd, 0xe2, 0xba, 0xb5, 0xa0, 0xb4, 0xde, 0xa7, 0xf5, 0x21, 0x78, 0x18, 0x93, 0x9f, 0x43, 0xa1,
	0x30, 0xb0, 0x18, 0x33, 0x73, 0x0a, 0x5a, 0xe3, 0x79, 0xcd, 0xa8, 0x25, 0xda, 0x68, 0xdb, 0xd3,
	0xb1, 0x64, 0x09, 0x57, 0xd7, 0x99, 0xd1, 0x1e, 0x19, 0xfd, 0x04, 0x1e, 0xe5, 0x97, 0xe7, 0xcb,
	0xa5, 0x47, 0x0e, 0x29, 0xe7, 0xfe, 0x52, 0x83, 0xde, 0xcf, 0xe5, 0x52, 0xc5, 0x78, 0xb7, 0x22,
	0x80, 0x0f, 0xe0, 0x20, 0x75, 0x98, 0xef, 0x0c, 0xab, 0xe3, 0xd6, 0xe4, 0x41, 0x01, 0x21, 0x2f,
	0x65, 0x4a, 0xaf, 0x67, 0x32, 0x36, 0x78, 0x6b, 0xbc, 0x8f, 0xa1, 0x55, 0xf0, 0x22, 0xf1, 0xc4,
	0xbf, 0x3f, 0x30, 0x80, 0x66, 0x0e, 0x4c, 0xed, 0x57, 0x87, 0xd5, 0x71, 0x8d, 0xc2, 0x18, 0xc9,
	0xe0, 0xfa, 0x46, 0x68, 0xa4, 0xbc, 0x6c, 0xec, 0x65, 0xb7, 0x7b, 0xd0, 0xa6, 0x64, 0xca, 0xb3,
	0xf8, 0x80, 0x52, 0xec, 0x08, 0x3a, 0x56, 0x6a, 0x14, 0x8f, 0xf5, 0x0c, 0x55, 0x9e, 0xb7, 0x3f,
	0x82, 0x7b, 0x9a, 0xf0, 0x18, 0xa7, 0x78, 0xb4, 0x6e, 0xe0, 0x0b, 0x4d, 0xa9, 0xdb, 0x9a, 0x3c,
	0x2a, 0x28, 0xb9, 0x0b, 0xb6, 0x27, 0x00, 0x37, 0x73, 0xc4, 0x28, 0x98, 0x73, 0xa1, 0x08, 0x4a,
	0x8d, 0xe7, 0xee, 0x8c, 0x47, 0x1a, 0x4b, 0x19, 0xd9, 0xa2, 0x8c, 0xec, 0x41, 0x3d, 0x44, 0xc3,
	0x45, 0xa4, 0x09, 0x1f, 0x8d, 0x1d, 0xf9, 0xd6, 0xdd, 0x9b, 0x6f, 0x43, 0x38, 0xb2, 0x06, 0xe0,
	0xad, 0x51, 0x9c, 0x69, 0x0c, 0x64, 0x1c, 0xb2, 0x84, 0x6b, 0x9d, 0x22, 0xe5, 0xb9, 0xf3, 0xd4,
	0x7b, 0x0c, 0x7e, 0x8e, 0xc6, 0xdc, 0x4c, 0x96, 0x60, 0xcc, 0x23, 0x73, 0x97, 0xc2, 0xe5, 0x79,
	0xf5, 0xd9, 0xe4, 0xa9, 0xf7, 0x10, 0xee, 0x15, 0xc0, 0xb2, 0xf6, 0xd3, 0x20, 0x67, 0x2b, 0x82,
	0xab, 0x88, 0x2d, 0x00, 0x3c, 0x52, 0xd3, 0xb2, 0x73, 0x14, 0xc9, 0x1b, 0x0c, 0x99, 0x08, 0xfd,
	0x43, 0xf2, 0xf2, 0x7b, 0xd0, 0x9f, 0x29, 0x44, 0xa6, 0x78, 0x28, 0x96, 0x9a, 0x59, 0x2a, 0xf5,
	0xef, 0xe5, 0x9a, 0x9c, 0x40, 0xb7, 0xb8, 0x68, 0xa4, 0x7f, 0x94, 0x2d, 0x8d, 0x7e, 0xeb, 0xc0,
	0x61, 0x5a, 0x4b, 0x5e, 0x23, 0x57, 0xd3, 0xbb, 0x1c, 0x50, 0x2d, 0xa8, 0x5a, 0x82, 0x4b, 0x39,
	0xdb, 0x92, 0xb0, 0xd0, 0x86, 0xc7, 0x01, 0x12, 0x5b, 0x3b, 0xeb, 0x2a, 0x53, 0x7d, 0xb7, 0x2a,
	0x53, 0xdb, 0xa4, 0x59, 0x37, 0xaf, 0x32, 0x05, 0x26, 0x4e, 0x71, 0xb1, 0xae, 0x99, 0x96, 0x1c,
	0x9a, 0xa3, 0xa7, 0xd0, 0x23, 0xf5, 0x7e, 0xa1, 0xc4, 0x1e, 0xd5, 0xb2, 0x17, 0x2a, 0xa9, 0x45,
	0xcf, 0x46, 0x7f, 0x77, 0xa0, 0x4f, 0x47, 0xce, 0x64, 0xb8, 0xaa, 0x47, 0xa7, 0x50, 0xa3, 0xaa,
	0x65, 0x0f, 0x75, 0x27, 0xc3, 0x82, 0xba, 0xe5, 0xad, 0xa7, 0xa4, 0xf8, 0x00, 0x9a, 0x76, 0x3f,
	0xc1, 0x25, 0x2b, 0x50, 0x6d, 0xa8, 0xd1, 0x97, 0x2d, 0x98, 0xcd, 0x91, 0x81, 0x1a, 0x6d, 0x6c,
	0x43, 0xc3, 0xd6, 0xbe, 0x4f, 0x15, 0xf2, 0xfe, 0x37, 0xbc, 0x16, 0xd4, 0x33, 0x44, 0xf6, 0x1d,
	0xfb, 0x71, 0x26, 0x17, 0x09, 0x8f, 0xef, 0xfa, 0x15, 0xaf, 0x01, 0x35, 0xdb, 0x53, 0xf4, 0xab,
	0x5e, 0x13, 0xdc, 0x0b, 0xb9, 0x34, 0xd8, 0xaf, 0x79, 0x1e, 0x74, 0x7f, 0x89, 0x73, 0x11, 0x44,
	0x98, 0xe5, 0x73, 0xdf, 0xfa, 0xa8, 0x69, 0x2f, 0x3c, 0x97, 0x22, 0x36, 0xfd, 0x03, 0x7b, 0x7f,
	0xde, 0xf1, 0xf5, 0xeb, 0xa3, 0x3f, 0x54, 0xa0, 0x7d, 0x7e, 0x79, 0x81, 0xb3, 0xb5, 0x5d, 0xdd,
	0xac, 0x73, 0xc4, 0x90, 0x15, 0x2c, 0xdc, 0x17, 0x90, 0xb5, 0x7b, 0x53, 0xa3, 0x4a, 0x6d, 0x40,
	0xb9, 0x8b, 0xda, 0x13, 0xb4, 0x75, 0x22, 0xd5, 0x09, 0x90, 0x4f, 0xa0, 0x29, 0x43, 0x93, 0xa5,
	0x4c, 0x83, 0x52, 0xe6, 0xb0, 0xa0, 0xc0, 0xe7, 0xa1, 0x49, 0x73, 0x66, 0xab, 0x7e, 0x1e, 0xe4,
	0xf5, 0x73, 0x55, 0xf8, 0x9a, 0x79, 0xe7, 0x53, 0xea, 0x88, 0x60, 0x4f, 0x47, 0xd4, 0x22, 0xf9,
	0x8e, 0x02, 0xd7, 0xa6, 0x02, 0x67, 0xe0, 0xe8, 0x8c, 0xab, 0xb3, 0xcf, 0x27, 0x3f, 0x5d, 0x08,
	0x6d, 0x9b, 0x80, 0x5d, 0x84, 0xe9, 0x7c, 0x55, 0xc2, 0xfc, 0x0f, 0x07, 0x46, 0x7f, 0x73, 0x60,
	0xf0, 0x13, 0xca, 0xe9, 0x73, 0x6e, 0xe6, 0xff, 0x8f, 0x27, 0x37, 0x7c, 0x98, 0x76, 0x4e, 0x3b,
	0x28, 0x7a, 0x1f, 0xbb, 0xba, 0xef, 0xc2, 0xae, 0xa3, 0x3f, 0x39, 0xf0, 0xad, 0x0d, 0xb9, 0x85,
	0xb1, 0x88, 0xaf, 0x5e, 0x71, 0xa3, 0xc4, 0x6d, 0x6e, 0xe5, 0x87, 0x50, 0x4f, 0xad, 0xd4, 0xef,
	0x50, 0x8a, 0x9e, 0x42, 0xbb, 0x60, 0xa6, 0x7e, 0x87, 0x5a, 0xd4, 0x86, 0xda, 0x22, 0xcd, 0xc2,
	0x6c, 0xaa, 0x49, 0x2b, 0xa8, 0x6d, 0xb0, 0x2b, 0x5b, 0xa5, 0x86, 0xfa, 0xfe, 0xd1, 0x0d, 0x74,
	0x5e, 0x71, 0x13, 0xcc, 0x45, 0x7c, 0x45, 0x89, 0x67, 0x7d, 0x15, 0x89, 0x18, 0x59, 0xca, 0x22,
	0xf6, 0x9e, 0x87, 0xd6, 0x31, 0x16, 0xf7, 0xb6, 0x8f, 0x64, 0x89, 0xcd, 0x3d, 0x5a, 0xad, 0xe4,
	0xab, 0xc5, 0xb6, 0xc3, 0x22, 0x9f, 0x5d, 0xe3, 0x5d, 0xa6, 0x43, 0xa9, 0x2d, 0x22, 0x8e, 0xa0,
	0x7e, 0x7f, 0xf4, 0xcf, 0x06, 0xd4, 0x73, 0xb7, 0x3c, 0x5e, 0x8d, 0x78, 0x18, 0x32, 0x9e, 0x88,
	0x2c, 0x4f, 0xbb, 0x05, 0x53, 0x3f, 0x3d, 0xff, 0xcc, 0x1b, 0xc3, 0x41, 0x42, 0x6c, 0x9c, 0x85,
	0xdc, 0x2f, 0x33, 0xd5, 0xaa, 0xe2, 0x7f, 0x02, 0xbd, 0x18, 0x6f, 0x33, 0x8d, 0xf3, 0xd2, 0x5c,
	0x0e, 0xe3, 0xae, 0xd6, 0xfc, 0x07, 0xd0, 0x49, 0x9f, 0x60, 0x31, 0x31, 0x3e, 0x29, 0xbb, 0x79,
	0x6c, 0x57, 0x41, 0xf8, 0x08, 0x1a, 0x6f, 0xb2, 0xa6, 0x23, 0xc3, 0x4b, 0x31, 0x4c, 0xe5, 0x7e,
	0xe4, 0x09, 0xb8, 0x89, 0x51, 0x38, 0xa3, 0x31, 0xa1, 0x35, 0xb9, 0x5f, 0xbc, 0xbc, 0xc8, 0x5f,
	0xdf, 0x85, 0x26, 0x29, 0x43, 0xde, 0xae, 0x6f, 0x5d, 0x5b, 0xa6, 0xfe, 0x1f, 0x42, 0xcf, 0xa4,
	0xa3, 0x26, 0x53, 0xe9, 0x74, 0x46, 0x95, 0xbb, 0xb5, 0xc1, 0xe8, 0xbb, 0x87, 0xd1, 0x53, 0xdb,
	0x78, 0x66, 0xa3, 0x33, 0xb1, 0x4c, 0x6b, 0xf2, 0x5e, 0xe1, 0xd0, 0xd6, 0x58, 0x7d, 0x0a, 0x90,
	0x18, 0x26, 0xa7, 0x6f, 0x30, 0x30, 0x9a, 0xe8, 0xa7, 0xa4, 0x9a, 0x49, 0xd7, 0xf2, 0xfd, 0x1f,
	0x03, 0xa4, 0x96, 0x10, 0x00, 0x5a, 0x5b, 0x0f, 0x6c, 0x95, 0xa4, 0x1f, 0xc3, 0xa1, 0x0d, 0x00,
	0xea, 0x22, 0xea, 0xd2, 0x61, 0xa1, 0x35, 0xf9, 0xf6, 0x46, 0x10, 0x69, 0xd7, 0xaa, 0x2a, 0xac,
	0x54, 0xdc, 0x39, 0x39, 0xa4, 0x43, 0xc5, 0x27, 0xd0, 0x14, 0x5a, 0x06, 0x73, 0x25, 0xe3, 0x74,
	0x98, 0x68, 0x4d, 0xbe, 0x53, 0xb8, 0xf2, 0x85, 0xe2, 0xc9, 0x5c, 0x04, 0x3c, 0xfa, 0x2c, 0xdf,
	0x94, 0xdf, 0xf9, 0x1c, 0xfa, 0xb6, 0x01, 0x0d, 0xe4, 0x84, 0x61, 0x46, 0x99, 0xd4, 0x89, 0x6c,
	0xba, 0x78, 0x37, 0xa7, 0x3e, 0x83, 0x56, 0xb1, 0xed, 0xf5, 0xe8, 0xd8, 0xc3, 0xc2, 0xb1, 0x6d,
	0x4e, 0xfc, 0x10, 0x1a, 0x73, 0xe4, 0x86, 0x2d, 0x78, 0x42, 0xdd, 0x6d, 0x6b, 0x72, 0x52, 0xd8,
	0xff, 0x33, 0xe4, 0xe6, 0x15, 0x4f, 0xf2, 0xcd, 0x2f, 0x60, 0xa0, 0x63, 0xa6, 0x52, 0xd6, 0x61,
	0x0b, 0xa2, 0x1d, 0x6a, 0x72, 0x5a, 0x93, 0x8f, 0xf6, 0x71, 0xd7, 0x1e, 0x8e, 0x72, 0x03, 0x29,
	0x55, 0x48, 0x6d, 0xd0, 0xa6, 0x8a, 0x2f, 0x50, 0x5e, 0xe5, 0xce, 0x39, 0xb3, 0x7b, 0xbc, 0x67,
	0xd0, 0x5b, 0x64, 0xf4, 0x41, 0x6f, 0xa3, 0xf6, 0xef, 0x6f, 0xe5, 0xe6, 0x26, 0xc1, 0x7c, 0x0f,
	0xda, 0x44, 0x30, 0x39, 0x46, 0x7d, 0xda, 0xff, 0x7e, 0x91, 0xd6, 0xb6, 0xff, 0x5f, 0xf0, 0x00,
	0x32, 0x86, 0xb0, 0x5d, 0x5d, 0x3a, 0xd4, 0xbc, 0x0f, 0x47, 0x79, 0x5d, 0x9b, 0x21, 0x86, 0xc9,
	0x72, 0x1a, 0x09, 0x3d, 0x47, 0xe5, 0x1f, 0x53, 0x75, 0xfb, 0x87, 0x03, 0xfe, 0x5e, 0x74, 0x74,
	0xc0, 0x25, 0x40, 0x66, 0x14, 0x97, 0x13, 0xe7, 0x57, 0x98, 0xd8, 0x6a, 0xdb, 0x13, 0x9b, 0xbb,
	0x3d, 0xb1, 0x1d, 0x90, 0xa8, 0xd4, 0xb7, 0x6d, 0x51, 0x71, 0x3a, 0x7b, 0xf7, 0xa0, 0xae, 0xd0,
	0x8e, 0xe3, 0x69, 0xa1, 0x6f, 0xec, 0x1e, 0x87, 0x6c, 0xb2, 0x39, 0xa3, 0x08, 0x4e, 0xf6, 0xc3,
	0xf4, 0xfb, 0xd0, 0xcf, 0xd9, 0x88, 0x65, 0x5e, 0xdb, 0x51, 0x55, 0xcb, 0xac, 0x74, 0x02, 0x83,
	0xa9, 0x5c, 0xda, 0x34, 0xbf, 0x5b, 0x6b, 0x66, 0x6b, 0x8e, 0x3b, 0xfa, 0x15, 0x74, 0x4b, 0x68,
	0xfb, 0xef, 0x9e, 0xa0, 0x28, 0x6a, 0x19, 0x2d, 0x57, 0x75, 0xdb, 0x1d, 0xfd, 0xde, 0x81, 0x5e,
	0x99, 0x2e, 0xbe, 0xae, 0x7f, 0x6c, 0x76, 0xb5, 0x4a, 0xd4, 0xc4, 0xfd, 0x2b, 0x00, 0x00, 0xff,
	0xff, 0x7c, 0x71, 0x4f, 0x59, 0x83, 0x14, 0x00, 0x00,
}
