// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stat.proto

package pbnavitia

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type StatParameter struct {
	Key              *string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StatParameter) Reset()                    { *m = StatParameter{} }
func (m *StatParameter) String() string            { return proto.CompactTextString(m) }
func (*StatParameter) ProtoMessage()               {}
func (*StatParameter) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *StatParameter) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *StatParameter) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type Filter struct {
	Object           *string `protobuf:"bytes,1,opt,name=object" json:"object,omitempty"`
	Attribute        *string `protobuf:"bytes,2,opt,name=attribute" json:"attribute,omitempty"`
	Operator         *string `protobuf:"bytes,3,opt,name=operator" json:"operator,omitempty"`
	Value            *string `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Filter) Reset()                    { *m = Filter{} }
func (m *Filter) String() string            { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()               {}
func (*Filter) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *Filter) GetObject() string {
	if m != nil && m.Object != nil {
		return *m.Object
	}
	return ""
}

func (m *Filter) GetAttribute() string {
	if m != nil && m.Attribute != nil {
		return *m.Attribute
	}
	return ""
}

func (m *Filter) GetOperator() string {
	if m != nil && m.Operator != nil {
		return *m.Operator
	}
	return ""
}

func (m *Filter) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type InterpretedParameter struct {
	Key              *string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            *string   `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Filters          []*Filter `protobuf:"bytes,3,rep,name=filters" json:"filters,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *InterpretedParameter) Reset()                    { *m = InterpretedParameter{} }
func (m *InterpretedParameter) String() string            { return proto.CompactTextString(m) }
func (*InterpretedParameter) ProtoMessage()               {}
func (*InterpretedParameter) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *InterpretedParameter) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *InterpretedParameter) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func (m *InterpretedParameter) GetFilters() []*Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

type StatError struct {
	Id               *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Message          *string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StatError) Reset()                    { *m = StatError{} }
func (m *StatError) String() string            { return proto.CompactTextString(m) }
func (*StatError) ProtoMessage()               {}
func (*StatError) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *StatError) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *StatError) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type StatCoverage struct {
	RegionId         *string `protobuf:"bytes,1,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StatCoverage) Reset()                    { *m = StatCoverage{} }
func (m *StatCoverage) String() string            { return proto.CompactTextString(m) }
func (*StatCoverage) ProtoMessage()               {}
func (*StatCoverage) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *StatCoverage) GetRegionId() string {
	if m != nil && m.RegionId != nil {
		return *m.RegionId
	}
	return ""
}

type StatRequest struct {
	// POSIX time (i.e., number of seconds since January 1st 1970 00:00:00 UTC)
	RequestDate           *uint64                 `protobuf:"varint,1,opt,name=request_date,json=requestDate" json:"request_date,omitempty"`
	UserId                *int32                  `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	UserName              *string                 `protobuf:"bytes,3,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	ApplicationId         *int32                  `protobuf:"varint,4,opt,name=application_id,json=applicationId" json:"application_id,omitempty"`
	ApplicationName       *string                 `protobuf:"bytes,5,opt,name=application_name,json=applicationName" json:"application_name,omitempty"`
	RequestDuration       *int32                  `protobuf:"varint,6,opt,name=request_duration,json=requestDuration" json:"request_duration,omitempty"`
	Api                   *string                 `protobuf:"bytes,7,opt,name=api" json:"api,omitempty"`
	Path                  *string                 `protobuf:"bytes,8,opt,name=path" json:"path,omitempty"`
	Host                  *string                 `protobuf:"bytes,10,opt,name=host" json:"host,omitempty"`
	ResponseSize          *int32                  `protobuf:"varint,11,opt,name=response_size,json=responseSize" json:"response_size,omitempty"`
	Client                *string                 `protobuf:"bytes,12,opt,name=client" json:"client,omitempty"`
	Coverages             []*StatCoverage         `protobuf:"bytes,13,rep,name=coverages" json:"coverages,omitempty"`
	Parameters            []*StatParameter        `protobuf:"bytes,14,rep,name=parameters" json:"parameters,omitempty"`
	Error                 *StatError              `protobuf:"bytes,15,opt,name=error" json:"error,omitempty"`
	Journeys              []*StatJourneyResponse  `protobuf:"bytes,16,rep,name=journeys" json:"journeys,omitempty"`
	InterpretedParameters []*InterpretedParameter `protobuf:"bytes,17,rep,name=interpreted_parameters,json=interpretedParameters" json:"interpreted_parameters,omitempty"`
	JourneyRequest        *JourneyRequest         `protobuf:"bytes,18,opt,name=journey_request,json=journeyRequest" json:"journey_request,omitempty"`
	EndPointId            *int32                  `protobuf:"varint,19,opt,name=end_point_id,json=endPointId" json:"end_point_id,omitempty"`
	EndPointName          *string                 `protobuf:"bytes,20,opt,name=end_point_name,json=endPointName" json:"end_point_name,omitempty"`
	InfoResponse          *StatInfoResponse       `protobuf:"bytes,21,opt,name=info_response,json=infoResponse" json:"info_response,omitempty"`
	Token                 *string                 `protobuf:"bytes,22,opt,name=token" json:"token,omitempty"`
	XXX_unrecognized      []byte                  `json:"-"`
}

func (m *StatRequest) Reset()                    { *m = StatRequest{} }
func (m *StatRequest) String() string            { return proto.CompactTextString(m) }
func (*StatRequest) ProtoMessage()               {}
func (*StatRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *StatRequest) GetRequestDate() uint64 {
	if m != nil && m.RequestDate != nil {
		return *m.RequestDate
	}
	return 0
}

func (m *StatRequest) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *StatRequest) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *StatRequest) GetApplicationId() int32 {
	if m != nil && m.ApplicationId != nil {
		return *m.ApplicationId
	}
	return 0
}

func (m *StatRequest) GetApplicationName() string {
	if m != nil && m.ApplicationName != nil {
		return *m.ApplicationName
	}
	return ""
}

func (m *StatRequest) GetRequestDuration() int32 {
	if m != nil && m.RequestDuration != nil {
		return *m.RequestDuration
	}
	return 0
}

func (m *StatRequest) GetApi() string {
	if m != nil && m.Api != nil {
		return *m.Api
	}
	return ""
}

func (m *StatRequest) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *StatRequest) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *StatRequest) GetResponseSize() int32 {
	if m != nil && m.ResponseSize != nil {
		return *m.ResponseSize
	}
	return 0
}

func (m *StatRequest) GetClient() string {
	if m != nil && m.Client != nil {
		return *m.Client
	}
	return ""
}

func (m *StatRequest) GetCoverages() []*StatCoverage {
	if m != nil {
		return m.Coverages
	}
	return nil
}

func (m *StatRequest) GetParameters() []*StatParameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *StatRequest) GetError() *StatError {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *StatRequest) GetJourneys() []*StatJourneyResponse {
	if m != nil {
		return m.Journeys
	}
	return nil
}

func (m *StatRequest) GetInterpretedParameters() []*InterpretedParameter {
	if m != nil {
		return m.InterpretedParameters
	}
	return nil
}

func (m *StatRequest) GetJourneyRequest() *JourneyRequest {
	if m != nil {
		return m.JourneyRequest
	}
	return nil
}

func (m *StatRequest) GetEndPointId() int32 {
	if m != nil && m.EndPointId != nil {
		return *m.EndPointId
	}
	return 0
}

func (m *StatRequest) GetEndPointName() string {
	if m != nil && m.EndPointName != nil {
		return *m.EndPointName
	}
	return ""
}

func (m *StatRequest) GetInfoResponse() *StatInfoResponse {
	if m != nil {
		return m.InfoResponse
	}
	return nil
}

func (m *StatRequest) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type JourneyRequest struct {
	// POSIX time (i.e., number of seconds since January 1st 1970 00:00:00 UTC)
	RequestedDateTime  *uint64 `protobuf:"varint,1,req,name=requested_date_time,json=requestedDateTime" json:"requested_date_time,omitempty"`
	Clockwise          *bool   `protobuf:"varint,2,req,name=clockwise" json:"clockwise,omitempty"`
	DepartureInsee     *string `protobuf:"bytes,3,opt,name=departure_insee,json=departureInsee" json:"departure_insee,omitempty"`
	DepartureAdmin     *string `protobuf:"bytes,4,opt,name=departure_admin,json=departureAdmin" json:"departure_admin,omitempty"`
	ArrivalInsee       *string `protobuf:"bytes,5,opt,name=arrival_insee,json=arrivalInsee" json:"arrival_insee,omitempty"`
	ArrivalAdmin       *string `protobuf:"bytes,6,opt,name=arrival_admin,json=arrivalAdmin" json:"arrival_admin,omitempty"`
	DepartureAdminName *string `protobuf:"bytes,7,opt,name=departure_admin_name,json=departureAdminName" json:"departure_admin_name,omitempty"`
	ArrivalAdminName   *string `protobuf:"bytes,8,opt,name=arrival_admin_name,json=arrivalAdminName" json:"arrival_admin_name,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *JourneyRequest) Reset()                    { *m = JourneyRequest{} }
func (m *JourneyRequest) String() string            { return proto.CompactTextString(m) }
func (*JourneyRequest) ProtoMessage()               {}
func (*JourneyRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *JourneyRequest) GetRequestedDateTime() uint64 {
	if m != nil && m.RequestedDateTime != nil {
		return *m.RequestedDateTime
	}
	return 0
}

func (m *JourneyRequest) GetClockwise() bool {
	if m != nil && m.Clockwise != nil {
		return *m.Clockwise
	}
	return false
}

func (m *JourneyRequest) GetDepartureInsee() string {
	if m != nil && m.DepartureInsee != nil {
		return *m.DepartureInsee
	}
	return ""
}

func (m *JourneyRequest) GetDepartureAdmin() string {
	if m != nil && m.DepartureAdmin != nil {
		return *m.DepartureAdmin
	}
	return ""
}

func (m *JourneyRequest) GetArrivalInsee() string {
	if m != nil && m.ArrivalInsee != nil {
		return *m.ArrivalInsee
	}
	return ""
}

func (m *JourneyRequest) GetArrivalAdmin() string {
	if m != nil && m.ArrivalAdmin != nil {
		return *m.ArrivalAdmin
	}
	return ""
}

func (m *JourneyRequest) GetDepartureAdminName() string {
	if m != nil && m.DepartureAdminName != nil {
		return *m.DepartureAdminName
	}
	return ""
}

func (m *JourneyRequest) GetArrivalAdminName() string {
	if m != nil && m.ArrivalAdminName != nil {
		return *m.ArrivalAdminName
	}
	return ""
}

type StatJourneyResponse struct {
	RequestedDateTime *uint64               `protobuf:"varint,1,opt,name=requested_date_time,json=requestedDateTime" json:"requested_date_time,omitempty"`
	DepartureDateTime *uint64               `protobuf:"varint,2,opt,name=departure_date_time,json=departureDateTime" json:"departure_date_time,omitempty"`
	ArrivalDateTime   *uint64               `protobuf:"varint,3,opt,name=arrival_date_time,json=arrivalDateTime" json:"arrival_date_time,omitempty"`
	Duration          *int32                `protobuf:"varint,4,opt,name=duration" json:"duration,omitempty"`
	NbTransfers       *int32                `protobuf:"varint,5,opt,name=nb_transfers,json=nbTransfers" json:"nb_transfers,omitempty"`
	Type              *string               `protobuf:"bytes,6,opt,name=type" json:"type,omitempty"`
	Sections          []*StatJourneySection `protobuf:"bytes,7,rep,name=sections" json:"sections,omitempty"`
	FirstPtId         *string               `protobuf:"bytes,8,opt,name=first_pt_id,json=firstPtId" json:"first_pt_id,omitempty"`
	FirstPtName       *string               `protobuf:"bytes,9,opt,name=first_pt_name,json=firstPtName" json:"first_pt_name,omitempty"`
	FirstPtCoord      *GeographicalCoord    `protobuf:"bytes,10,opt,name=first_pt_coord,json=firstPtCoord" json:"first_pt_coord,omitempty"`
	FirstPtAdminId    *string               `protobuf:"bytes,11,opt,name=first_pt_admin_id,json=firstPtAdminId" json:"first_pt_admin_id,omitempty"`
	FirstPtAdminName  *string               `protobuf:"bytes,12,opt,name=first_pt_admin_name,json=firstPtAdminName" json:"first_pt_admin_name,omitempty"`
	FirstPtAdminInsee *string               `protobuf:"bytes,13,opt,name=first_pt_admin_insee,json=firstPtAdminInsee" json:"first_pt_admin_insee,omitempty"`
	LastPtId          *string               `protobuf:"bytes,14,opt,name=last_pt_id,json=lastPtId" json:"last_pt_id,omitempty"`
	LastPtName        *string               `protobuf:"bytes,15,opt,name=last_pt_name,json=lastPtName" json:"last_pt_name,omitempty"`
	LastPtCoord       *GeographicalCoord    `protobuf:"bytes,16,opt,name=last_pt_coord,json=lastPtCoord" json:"last_pt_coord,omitempty"`
	LastPtAdminId     *string               `protobuf:"bytes,17,opt,name=last_pt_admin_id,json=lastPtAdminId" json:"last_pt_admin_id,omitempty"`
	LastPtAdminName   *string               `protobuf:"bytes,18,opt,name=last_pt_admin_name,json=lastPtAdminName" json:"last_pt_admin_name,omitempty"`
	LastPtAdminInsee  *string               `protobuf:"bytes,19,opt,name=last_pt_admin_insee,json=lastPtAdminInsee" json:"last_pt_admin_insee,omitempty"`
	XXX_unrecognized  []byte                `json:"-"`
}

func (m *StatJourneyResponse) Reset()                    { *m = StatJourneyResponse{} }
func (m *StatJourneyResponse) String() string            { return proto.CompactTextString(m) }
func (*StatJourneyResponse) ProtoMessage()               {}
func (*StatJourneyResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *StatJourneyResponse) GetRequestedDateTime() uint64 {
	if m != nil && m.RequestedDateTime != nil {
		return *m.RequestedDateTime
	}
	return 0
}

func (m *StatJourneyResponse) GetDepartureDateTime() uint64 {
	if m != nil && m.DepartureDateTime != nil {
		return *m.DepartureDateTime
	}
	return 0
}

func (m *StatJourneyResponse) GetArrivalDateTime() uint64 {
	if m != nil && m.ArrivalDateTime != nil {
		return *m.ArrivalDateTime
	}
	return 0
}

func (m *StatJourneyResponse) GetDuration() int32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *StatJourneyResponse) GetNbTransfers() int32 {
	if m != nil && m.NbTransfers != nil {
		return *m.NbTransfers
	}
	return 0
}

func (m *StatJourneyResponse) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *StatJourneyResponse) GetSections() []*StatJourneySection {
	if m != nil {
		return m.Sections
	}
	return nil
}

func (m *StatJourneyResponse) GetFirstPtId() string {
	if m != nil && m.FirstPtId != nil {
		return *m.FirstPtId
	}
	return ""
}

func (m *StatJourneyResponse) GetFirstPtName() string {
	if m != nil && m.FirstPtName != nil {
		return *m.FirstPtName
	}
	return ""
}

func (m *StatJourneyResponse) GetFirstPtCoord() *GeographicalCoord {
	if m != nil {
		return m.FirstPtCoord
	}
	return nil
}

func (m *StatJourneyResponse) GetFirstPtAdminId() string {
	if m != nil && m.FirstPtAdminId != nil {
		return *m.FirstPtAdminId
	}
	return ""
}

func (m *StatJourneyResponse) GetFirstPtAdminName() string {
	if m != nil && m.FirstPtAdminName != nil {
		return *m.FirstPtAdminName
	}
	return ""
}

func (m *StatJourneyResponse) GetFirstPtAdminInsee() string {
	if m != nil && m.FirstPtAdminInsee != nil {
		return *m.FirstPtAdminInsee
	}
	return ""
}

func (m *StatJourneyResponse) GetLastPtId() string {
	if m != nil && m.LastPtId != nil {
		return *m.LastPtId
	}
	return ""
}

func (m *StatJourneyResponse) GetLastPtName() string {
	if m != nil && m.LastPtName != nil {
		return *m.LastPtName
	}
	return ""
}

func (m *StatJourneyResponse) GetLastPtCoord() *GeographicalCoord {
	if m != nil {
		return m.LastPtCoord
	}
	return nil
}

func (m *StatJourneyResponse) GetLastPtAdminId() string {
	if m != nil && m.LastPtAdminId != nil {
		return *m.LastPtAdminId
	}
	return ""
}

func (m *StatJourneyResponse) GetLastPtAdminName() string {
	if m != nil && m.LastPtAdminName != nil {
		return *m.LastPtAdminName
	}
	return ""
}

func (m *StatJourneyResponse) GetLastPtAdminInsee() string {
	if m != nil && m.LastPtAdminInsee != nil {
		return *m.LastPtAdminInsee
	}
	return ""
}

type StatJourneySection struct {
	DepartureDateTime  *uint64            `protobuf:"varint,1,opt,name=departure_date_time,json=departureDateTime" json:"departure_date_time,omitempty"`
	ArrivalDateTime    *uint64            `protobuf:"varint,2,opt,name=arrival_date_time,json=arrivalDateTime" json:"arrival_date_time,omitempty"`
	Duration           *int32             `protobuf:"varint,3,opt,name=duration" json:"duration,omitempty"`
	Type               *string            `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	Mode               *string            `protobuf:"bytes,5,opt,name=mode" json:"mode,omitempty"`
	FromEmbeddedType   *string            `protobuf:"bytes,6,opt,name=from_embedded_type,json=fromEmbeddedType" json:"from_embedded_type,omitempty"`
	FromId             *string            `protobuf:"bytes,7,opt,name=from_id,json=fromId" json:"from_id,omitempty"`
	FromName           *string            `protobuf:"bytes,8,opt,name=from_name,json=fromName" json:"from_name,omitempty"`
	FromCoord          *GeographicalCoord `protobuf:"bytes,9,opt,name=from_coord,json=fromCoord" json:"from_coord,omitempty"`
	FromAdminId        *string            `protobuf:"bytes,10,opt,name=from_admin_id,json=fromAdminId" json:"from_admin_id,omitempty"`
	FromAdminName      *string            `protobuf:"bytes,11,opt,name=from_admin_name,json=fromAdminName" json:"from_admin_name,omitempty"`
	ToEmbeddedType     *string            `protobuf:"bytes,12,opt,name=to_embedded_type,json=toEmbeddedType" json:"to_embedded_type,omitempty"`
	ToId               *string            `protobuf:"bytes,13,opt,name=to_id,json=toId" json:"to_id,omitempty"`
	ToName             *string            `protobuf:"bytes,14,opt,name=to_name,json=toName" json:"to_name,omitempty"`
	ToCoord            *GeographicalCoord `protobuf:"bytes,15,opt,name=to_coord,json=toCoord" json:"to_coord,omitempty"`
	ToAdminId          *string            `protobuf:"bytes,16,opt,name=to_admin_id,json=toAdminId" json:"to_admin_id,omitempty"`
	ToAdminName        *string            `protobuf:"bytes,17,opt,name=to_admin_name,json=toAdminName" json:"to_admin_name,omitempty"`
	VehicleJourneyId   *string            `protobuf:"bytes,18,opt,name=vehicle_journey_id,json=vehicleJourneyId" json:"vehicle_journey_id,omitempty"`
	LineId             *string            `protobuf:"bytes,19,opt,name=line_id,json=lineId" json:"line_id,omitempty"`
	LineCode           *string            `protobuf:"bytes,20,opt,name=line_code,json=lineCode" json:"line_code,omitempty"`
	RouteId            *string            `protobuf:"bytes,21,opt,name=route_id,json=routeId" json:"route_id,omitempty"`
	NetworkId          *string            `protobuf:"bytes,22,opt,name=network_id,json=networkId" json:"network_id,omitempty"`
	NetworkName        *string            `protobuf:"bytes,23,opt,name=network_name,json=networkName" json:"network_name,omitempty"`
	PhysicalModeId     *string            `protobuf:"bytes,24,opt,name=physical_mode_id,json=physicalModeId" json:"physical_mode_id,omitempty"`
	PhysicalModeName   *string            `protobuf:"bytes,25,opt,name=physical_mode_name,json=physicalModeName" json:"physical_mode_name,omitempty"`
	CommercialModeId   *string            `protobuf:"bytes,26,opt,name=commercial_mode_id,json=commercialModeId" json:"commercial_mode_id,omitempty"`
	CommercialModeName *string            `protobuf:"bytes,27,opt,name=commercial_mode_name,json=commercialModeName" json:"commercial_mode_name,omitempty"`
	FromAdminInsee     *string            `protobuf:"bytes,28,opt,name=from_admin_insee,json=fromAdminInsee" json:"from_admin_insee,omitempty"`
	ToAdminInsee       *string            `protobuf:"bytes,29,opt,name=to_admin_insee,json=toAdminInsee" json:"to_admin_insee,omitempty"`
	XXX_unrecognized   []byte             `json:"-"`
}

func (m *StatJourneySection) Reset()                    { *m = StatJourneySection{} }
func (m *StatJourneySection) String() string            { return proto.CompactTextString(m) }
func (*StatJourneySection) ProtoMessage()               {}
func (*StatJourneySection) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

func (m *StatJourneySection) GetDepartureDateTime() uint64 {
	if m != nil && m.DepartureDateTime != nil {
		return *m.DepartureDateTime
	}
	return 0
}

func (m *StatJourneySection) GetArrivalDateTime() uint64 {
	if m != nil && m.ArrivalDateTime != nil {
		return *m.ArrivalDateTime
	}
	return 0
}

func (m *StatJourneySection) GetDuration() int32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *StatJourneySection) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *StatJourneySection) GetMode() string {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return ""
}

func (m *StatJourneySection) GetFromEmbeddedType() string {
	if m != nil && m.FromEmbeddedType != nil {
		return *m.FromEmbeddedType
	}
	return ""
}

func (m *StatJourneySection) GetFromId() string {
	if m != nil && m.FromId != nil {
		return *m.FromId
	}
	return ""
}

func (m *StatJourneySection) GetFromName() string {
	if m != nil && m.FromName != nil {
		return *m.FromName
	}
	return ""
}

func (m *StatJourneySection) GetFromCoord() *GeographicalCoord {
	if m != nil {
		return m.FromCoord
	}
	return nil
}

func (m *StatJourneySection) GetFromAdminId() string {
	if m != nil && m.FromAdminId != nil {
		return *m.FromAdminId
	}
	return ""
}

func (m *StatJourneySection) GetFromAdminName() string {
	if m != nil && m.FromAdminName != nil {
		return *m.FromAdminName
	}
	return ""
}

func (m *StatJourneySection) GetToEmbeddedType() string {
	if m != nil && m.ToEmbeddedType != nil {
		return *m.ToEmbeddedType
	}
	return ""
}

func (m *StatJourneySection) GetToId() string {
	if m != nil && m.ToId != nil {
		return *m.ToId
	}
	return ""
}

func (m *StatJourneySection) GetToName() string {
	if m != nil && m.ToName != nil {
		return *m.ToName
	}
	return ""
}

func (m *StatJourneySection) GetToCoord() *GeographicalCoord {
	if m != nil {
		return m.ToCoord
	}
	return nil
}

func (m *StatJourneySection) GetToAdminId() string {
	if m != nil && m.ToAdminId != nil {
		return *m.ToAdminId
	}
	return ""
}

func (m *StatJourneySection) GetToAdminName() string {
	if m != nil && m.ToAdminName != nil {
		return *m.ToAdminName
	}
	return ""
}

func (m *StatJourneySection) GetVehicleJourneyId() string {
	if m != nil && m.VehicleJourneyId != nil {
		return *m.VehicleJourneyId
	}
	return ""
}

func (m *StatJourneySection) GetLineId() string {
	if m != nil && m.LineId != nil {
		return *m.LineId
	}
	return ""
}

func (m *StatJourneySection) GetLineCode() string {
	if m != nil && m.LineCode != nil {
		return *m.LineCode
	}
	return ""
}

func (m *StatJourneySection) GetRouteId() string {
	if m != nil && m.RouteId != nil {
		return *m.RouteId
	}
	return ""
}

func (m *StatJourneySection) GetNetworkId() string {
	if m != nil && m.NetworkId != nil {
		return *m.NetworkId
	}
	return ""
}

func (m *StatJourneySection) GetNetworkName() string {
	if m != nil && m.NetworkName != nil {
		return *m.NetworkName
	}
	return ""
}

func (m *StatJourneySection) GetPhysicalModeId() string {
	if m != nil && m.PhysicalModeId != nil {
		return *m.PhysicalModeId
	}
	return ""
}

func (m *StatJourneySection) GetPhysicalModeName() string {
	if m != nil && m.PhysicalModeName != nil {
		return *m.PhysicalModeName
	}
	return ""
}

func (m *StatJourneySection) GetCommercialModeId() string {
	if m != nil && m.CommercialModeId != nil {
		return *m.CommercialModeId
	}
	return ""
}

func (m *StatJourneySection) GetCommercialModeName() string {
	if m != nil && m.CommercialModeName != nil {
		return *m.CommercialModeName
	}
	return ""
}

func (m *StatJourneySection) GetFromAdminInsee() string {
	if m != nil && m.FromAdminInsee != nil {
		return *m.FromAdminInsee
	}
	return ""
}

func (m *StatJourneySection) GetToAdminInsee() string {
	if m != nil && m.ToAdminInsee != nil {
		return *m.ToAdminInsee
	}
	return ""
}

type StatInfoResponse struct {
	ObjectCount      *int32 `protobuf:"varint,1,opt,name=object_count,json=objectCount" json:"object_count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *StatInfoResponse) Reset()                    { *m = StatInfoResponse{} }
func (m *StatInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*StatInfoResponse) ProtoMessage()               {}
func (*StatInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

func (m *StatInfoResponse) GetObjectCount() int32 {
	if m != nil && m.ObjectCount != nil {
		return *m.ObjectCount
	}
	return 0
}

func init() {
	proto.RegisterType((*StatParameter)(nil), "pbnavitia.StatParameter")
	proto.RegisterType((*Filter)(nil), "pbnavitia.Filter")
	proto.RegisterType((*InterpretedParameter)(nil), "pbnavitia.InterpretedParameter")
	proto.RegisterType((*StatError)(nil), "pbnavitia.StatError")
	proto.RegisterType((*StatCoverage)(nil), "pbnavitia.StatCoverage")
	proto.RegisterType((*StatRequest)(nil), "pbnavitia.StatRequest")
	proto.RegisterType((*JourneyRequest)(nil), "pbnavitia.JourneyRequest")
	proto.RegisterType((*StatJourneyResponse)(nil), "pbnavitia.StatJourneyResponse")
	proto.RegisterType((*StatJourneySection)(nil), "pbnavitia.StatJourneySection")
	proto.RegisterType((*StatInfoResponse)(nil), "pbnavitia.StatInfoResponse")
}

func init() { proto.RegisterFile("stat.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 1424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xdd, 0x6e, 0x1b, 0xb7,
	0x12, 0x86, 0x65, 0x5b, 0x96, 0x46, 0xff, 0x94, 0x12, 0x6f, 0x1c, 0x27, 0xc7, 0x47, 0x27, 0xe7,
	0xc4, 0xf9, 0xf3, 0x09, 0x02, 0x04, 0xe9, 0xcf, 0x4d, 0x1b, 0x37, 0x2d, 0x54, 0xa0, 0x45, 0xb0,
	0x09, 0x7a, 0xbb, 0xa0, 0xb5, 0xb4, 0xcd, 0x58, 0x5a, 0x6e, 0xb9, 0x94, 0x03, 0xe7, 0xe5, 0x7a,
	0xdd, 0x57, 0xe8, 0x4b, 0xf4, 0x15, 0x8a, 0x99, 0x21, 0x57, 0x2b, 0xd5, 0x41, 0x93, 0xbb, 0xe5,
	0xcc, 0xc7, 0x6f, 0xfe, 0x87, 0x12, 0x40, 0xe1, 0xa4, 0x3b, 0xca, 0xad, 0x71, 0x46, 0x34, 0xf3,
	0x93, 0x4c, 0x5e, 0x6a, 0xa7, 0xe5, 0x1e, 0xb8, 0xab, 0x5c, 0xb1, 0x78, 0xfc, 0x02, 0x3a, 0x6f,
	0x9c, 0x74, 0xaf, 0xa5, 0x95, 0x73, 0xe5, 0x94, 0x15, 0x7d, 0xd8, 0xbc, 0x50, 0x57, 0xd1, 0xc6,
	0xc1, 0xc6, 0x61, 0x33, 0xc6, 0x4f, 0x31, 0x82, 0xed, 0x4b, 0x39, 0x5b, 0xa8, 0xa8, 0x46, 0x32,
	0x3e, 0x8c, 0x73, 0xa8, 0x7f, 0xaf, 0x67, 0x78, 0xe3, 0x26, 0xd4, 0xcd, 0xc9, 0x3b, 0x35, 0x75,
	0xfe, 0x92, 0x3f, 0x89, 0x7d, 0x68, 0x4a, 0xe7, 0xac, 0x3e, 0x59, 0xb8, 0x70, 0x77, 0x29, 0x10,
	0x7b, 0xd0, 0x30, 0xb9, 0xb2, 0xd2, 0x19, 0x1b, 0x6d, 0x92, 0xb2, 0x3c, 0x2f, 0x2d, 0x6e, 0x55,
	0x2d, 0x5e, 0xc0, 0x68, 0x92, 0x39, 0x65, 0x73, 0xab, 0x9c, 0x4a, 0x3f, 0xdb, 0x63, 0xf1, 0x08,
	0x76, 0x4e, 0xc9, 0xe3, 0x22, 0xda, 0x3c, 0xd8, 0x3c, 0x6c, 0x3d, 0x1b, 0x1c, 0x95, 0x39, 0x39,
	0xe2, 0x58, 0xe2, 0x80, 0x18, 0x3f, 0x87, 0x26, 0xe6, 0xe5, 0x95, 0xb5, 0xc6, 0x8a, 0x2e, 0xd4,
	0x74, 0xea, 0x0d, 0xd4, 0x74, 0x2a, 0x22, 0xd8, 0x99, 0xab, 0xa2, 0x90, 0x67, 0xc1, 0x42, 0x38,
	0x8e, 0x1f, 0x41, 0x1b, 0xaf, 0x1d, 0x9b, 0x4b, 0x65, 0xe5, 0x99, 0x12, 0xb7, 0xa1, 0x69, 0xd5,
	0x99, 0x36, 0x59, 0x52, 0x12, 0x34, 0x58, 0x30, 0x49, 0xc7, 0x7f, 0xd6, 0xa1, 0x85, 0xe8, 0x58,
	0xfd, 0xba, 0x50, 0x85, 0x13, 0xff, 0x86, 0xb6, 0xe5, 0xcf, 0x24, 0x95, 0x4e, 0x11, 0x7e, 0x2b,
	0x6e, 0x79, 0xd9, 0x77, 0xd2, 0x29, 0xb1, 0x0b, 0x3b, 0x8b, 0x42, 0x59, 0x64, 0x43, 0xcb, 0xdb,
	0x71, 0x1d, 0x8f, 0x93, 0x14, 0x0d, 0x91, 0x22, 0x93, 0x73, 0x15, 0xf2, 0x89, 0x82, 0x9f, 0xe5,
	0x5c, 0x89, 0xff, 0x42, 0x57, 0xe6, 0xf9, 0x4c, 0x4f, 0xa5, 0xf3, 0xae, 0x6c, 0xd1, 0xe5, 0x4e,
	0x45, 0x3a, 0x49, 0xc5, 0x03, 0xe8, 0x57, 0x61, 0x44, 0xb5, 0x4d, 0x54, 0xbd, 0x8a, 0x9c, 0x18,
	0x1f, 0x40, 0xbf, 0x74, 0x75, 0x61, 0x49, 0x1e, 0xd5, 0x89, 0xb3, 0x17, 0xdc, 0xf5, 0x62, 0x2c,
	0x8f, 0xcc, 0x75, 0xb4, 0xc3, 0xe5, 0x91, 0xb9, 0x16, 0x02, 0xb6, 0x72, 0xe9, 0xce, 0xa3, 0x06,
	0x89, 0xe8, 0x1b, 0x65, 0xe7, 0xa6, 0x70, 0x11, 0xb0, 0x0c, 0xbf, 0xc5, 0x7f, 0xa0, 0x63, 0x55,
	0x91, 0x9b, 0xac, 0x50, 0x49, 0xa1, 0x3f, 0xa8, 0xa8, 0x45, 0x16, 0xda, 0x41, 0xf8, 0x46, 0x7f,
	0x50, 0xd8, 0x7d, 0xd3, 0x99, 0x56, 0x99, 0x8b, 0xda, 0xdc, 0x7d, 0x7c, 0x12, 0xcf, 0xa1, 0x39,
	0xf5, 0x55, 0x28, 0xa2, 0x0e, 0xd5, 0x7b, 0xb7, 0x52, 0xef, 0x6a, 0x95, 0xe2, 0x25, 0x52, 0x7c,
	0x01, 0x90, 0x87, 0xce, 0x2a, 0xa2, 0x2e, 0xdd, 0x8b, 0xd6, 0xee, 0x95, 0xad, 0x17, 0x57, 0xb0,
	0xe2, 0x21, 0x6c, 0x2b, 0xec, 0x96, 0xa8, 0x77, 0xb0, 0x71, 0xd8, 0x7a, 0x36, 0x5a, 0xbb, 0x44,
	0x9d, 0x14, 0x33, 0x44, 0x7c, 0x05, 0x8d, 0x77, 0x66, 0x61, 0x33, 0x75, 0x55, 0x44, 0x7d, 0xb2,
	0x71, 0x77, 0x0d, 0xfe, 0x23, 0xab, 0x63, 0x1f, 0x6a, 0x5c, 0xe2, 0xc5, 0x2f, 0x70, 0x53, 0x2f,
	0xc7, 0x20, 0xa9, 0x78, 0x3b, 0x20, 0xa6, 0x7f, 0x55, 0x98, 0xae, 0x9b, 0x97, 0xf8, 0x86, 0xbe,
	0x46, 0x5a, 0x88, 0x97, 0xd0, 0xf3, 0x36, 0x12, 0x5f, 0xc2, 0x48, 0x50, 0x24, 0xb7, 0x2a, 0x84,
	0xa5, 0x5b, 0x04, 0x88, 0xbb, 0xef, 0x56, 0xce, 0xe2, 0x00, 0xda, 0x2a, 0x4b, 0x93, 0xdc, 0xe8,
	0xcc, 0x61, 0x9b, 0x0d, 0xa9, 0x60, 0xa0, 0xb2, 0xf4, 0x35, 0x8a, 0x26, 0xa9, 0xb8, 0x07, 0xdd,
	0x25, 0x82, 0x3a, 0x6c, 0x44, 0x65, 0x6b, 0x07, 0x0c, 0xb5, 0xd7, 0x37, 0xd0, 0xd1, 0xd9, 0xa9,
	0x49, 0x42, 0xa5, 0xa3, 0x1b, 0xe4, 0xc9, 0xed, 0xb5, 0x24, 0x4d, 0xb2, 0x53, 0x53, 0x66, 0xa8,
	0xad, 0x2b, 0x27, 0x5c, 0x01, 0xce, 0x5c, 0xa8, 0x2c, 0xba, 0xc9, 0x2b, 0x80, 0x0e, 0xe3, 0x3f,
	0x6a, 0xd0, 0x5d, 0x0d, 0x41, 0x1c, 0xc1, 0xd0, 0x87, 0xab, 0x52, 0x1a, 0xbb, 0xc4, 0xe9, 0x39,
	0xce, 0x5e, 0xed, 0x70, 0x2b, 0x1e, 0x94, 0x2a, 0x9c, 0xbe, 0xb7, 0x7a, 0xae, 0x70, 0xab, 0x4d,
	0x67, 0x66, 0x7a, 0xf1, 0x5e, 0x17, 0x38, 0xfd, 0xb5, 0xc3, 0x46, 0xbc, 0x14, 0x88, 0xfb, 0xd0,
	0x4b, 0x55, 0x2e, 0xad, 0x5b, 0x58, 0x95, 0xe8, 0xac, 0x50, 0x61, 0x18, 0xbb, 0xa5, 0x78, 0x82,
	0xd2, 0x55, 0xa0, 0x4c, 0xe7, 0x3a, 0xf3, 0xcb, 0x6e, 0x09, 0xfc, 0x16, 0xa5, 0x38, 0x04, 0xd2,
	0x5a, 0x7d, 0x29, 0x67, 0x9e, 0x8f, 0x27, 0xb2, 0xed, 0x85, 0xcc, 0x56, 0x01, 0x31, 0x57, 0x7d,
	0x05, 0xc4, 0x4c, 0x4f, 0x61, 0xb4, 0x66, 0x92, 0x0b, 0xc0, 0x93, 0x29, 0x56, 0xed, 0x52, 0x19,
	0x1e, 0x83, 0x58, 0xa1, 0x65, 0x3c, 0x8f, 0x6d, 0xbf, 0xca, 0x8d, 0xe8, 0xf1, 0xef, 0x75, 0x18,
	0x5e, 0xd3, 0xba, 0x1f, 0xcf, 0xf0, 0xc6, 0xf5, 0x19, 0x3e, 0x82, 0xe1, 0xd2, 0xcf, 0x25, 0xbe,
	0xc6, 0xf8, 0x52, 0x55, 0xe2, 0x1f, 0xc2, 0x20, 0x78, 0xb9, 0x44, 0x6f, 0x12, 0xba, 0xe7, 0x15,
	0x25, 0x76, 0x0f, 0x1a, 0xe5, 0xbe, 0xe2, 0x1d, 0x58, 0x9e, 0x71, 0xfd, 0x66, 0x27, 0x89, 0xb3,
	0x32, 0x2b, 0x4e, 0x71, 0x9c, 0xb6, 0x49, 0xdf, 0xca, 0x4e, 0xde, 0x06, 0x11, 0x6e, 0x29, 0x7c,
	0x3b, 0x7d, 0x7a, 0xe9, 0x5b, 0x7c, 0x09, 0x8d, 0x42, 0x4d, 0x91, 0xa1, 0x88, 0x76, 0x68, 0x02,
	0xef, 0x5c, 0x3f, 0xcb, 0x6f, 0x18, 0x15, 0x97, 0x70, 0x71, 0x17, 0x5a, 0xa7, 0xda, 0x16, 0x2e,
	0xc9, 0x69, 0x5a, 0x38, 0xb1, 0x4d, 0x12, 0xbd, 0xc6, 0x61, 0x19, 0x43, 0xa7, 0xd4, 0x53, 0xea,
	0x9b, 0x84, 0x68, 0x79, 0x04, 0xd5, 0xe8, 0x25, 0x74, 0x4b, 0xcc, 0xd4, 0x18, 0x9b, 0xd2, 0x0a,
	0x6d, 0x3d, 0xdb, 0xaf, 0x38, 0xf1, 0x83, 0x32, 0x67, 0x56, 0xe6, 0xe7, 0x7a, 0x2a, 0x67, 0xc7,
	0x88, 0x89, 0xdb, 0x9e, 0x82, 0x4e, 0xe2, 0x01, 0x0c, 0x4a, 0x0e, 0x2e, 0xb4, 0x4e, 0x69, 0xd9,
	0x36, 0xe3, 0xae, 0x07, 0x52, 0x99, 0x27, 0xa9, 0x78, 0x02, 0xc3, 0x35, 0x28, 0x39, 0xc6, 0xbb,
	0xb7, 0x5f, 0x05, 0x93, 0x77, 0xff, 0x87, 0xd1, 0x3a, 0x33, 0x35, 0x71, 0x87, 0xf0, 0x83, 0x15,
	0x72, 0xea, 0xe4, 0x7d, 0x80, 0x99, 0x2c, 0x33, 0xd2, 0xe5, 0x87, 0x0c, 0x25, 0x94, 0x90, 0x03,
	0x68, 0x07, 0x2d, 0x99, 0xed, 0x91, 0x1e, 0x58, 0x1f, 0x36, 0x47, 0x40, 0x70, 0x36, 0xfa, 0x9f,
	0x90, 0x8d, 0x16, 0x13, 0x70, 0x32, 0xee, 0x43, 0x3f, 0x30, 0x94, 0xb9, 0x18, 0x90, 0x9d, 0x0e,
	0xc3, 0x42, 0x2a, 0x1e, 0x81, 0x58, 0x05, 0x92, 0x4b, 0x82, 0x1f, 0xcc, 0x0a, 0x94, 0xfc, 0x7a,
	0x02, 0xc3, 0x35, 0x56, 0xca, 0xc3, 0x90, 0xf3, 0x56, 0x25, 0x46, 0xf9, 0xf8, 0xb7, 0x06, 0x88,
	0xbf, 0xb7, 0xce, 0xc7, 0x46, 0x63, 0xe3, 0xb3, 0x46, 0xa3, 0xf6, 0xcf, 0xa3, 0xb1, 0xb9, 0x36,
	0x1a, 0xa1, 0xef, 0xb7, 0x2a, 0x7d, 0x2f, 0x60, 0x6b, 0x6e, 0xd2, 0xb0, 0x8f, 0xe8, 0x1b, 0x17,
	0xc6, 0xa9, 0x35, 0xf3, 0x44, 0xcd, 0x4f, 0x54, 0x9a, 0xaa, 0x34, 0xa9, 0x4c, 0x4b, 0x1f, 0x35,
	0xaf, 0xbc, 0xe2, 0x2d, 0x32, 0xec, 0xc2, 0x0e, 0xa1, 0x75, 0xea, 0x77, 0x50, 0x1d, 0x8f, 0xfc,
	0x63, 0x86, 0x14, 0x95, 0x75, 0xd3, 0x40, 0x01, 0x65, 0xf2, 0x6b, 0x00, 0x52, 0x72, 0x79, 0x9b,
	0x9f, 0x50, 0x5e, 0x22, 0xe3, 0xe2, 0xe2, 0x44, 0xe1, 0xe5, 0xb2, 0xb2, 0xe0, 0x27, 0xca, 0x9a,
	0x79, 0xa8, 0xeb, 0xff, 0xa0, 0x57, 0xc1, 0x90, 0x0f, 0x3c, 0x0b, 0x9d, 0x12, 0x45, 0x8e, 0x1c,
	0x42, 0xdf, 0x99, 0xb5, 0x50, 0x79, 0x0e, 0xba, 0xce, 0xac, 0x04, 0x3a, 0xc4, 0xc7, 0x08, 0xad,
	0x75, 0x7c, 0xfe, 0xcc, 0x24, 0xc5, 0xe8, 0x9d, 0x61, 0x7a, 0x6e, 0xf3, 0xba, 0x33, 0xc4, 0xfb,
	0x02, 0x1a, 0xce, 0xf8, 0xf0, 0x7a, 0x9f, 0x10, 0xde, 0x8e, 0x33, 0x1c, 0xdc, 0x5d, 0x68, 0x39,
	0xb3, 0x0c, 0xad, 0xcf, 0xeb, 0xc4, 0x99, 0x10, 0xd8, 0x18, 0x3a, 0xa5, 0x9e, 0xec, 0x72, 0x5b,
	0xb7, 0x3c, 0x22, 0xac, 0xfc, 0x4b, 0x75, 0xae, 0xa7, 0x33, 0x95, 0x84, 0x5f, 0x03, 0x3a, 0xf5,
	0x4d, 0xdd, 0xf7, 0x1a, 0xdf, 0x94, 0x1c, 0xc3, 0x4c, 0x67, 0x2a, 0x3c, 0xf5, 0xcd, 0xb8, 0x8e,
	0x47, 0xae, 0x20, 0x29, 0xa6, 0xd8, 0x21, 0x23, 0x3f, 0xc5, 0x3a, 0x53, 0xc7, 0xd8, 0x25, 0xb7,
	0xa0, 0x61, 0xcd, 0xc2, 0xd1, 0xb5, 0x1b, 0xfc, 0xfb, 0x99, 0xce, 0x93, 0x54, 0xdc, 0x01, 0xc8,
	0x94, 0x7b, 0x6f, 0xec, 0x05, 0x2a, 0xf9, 0xed, 0x6e, 0x7a, 0xc9, 0x24, 0xa5, 0x15, 0xed, 0xd5,
	0x14, 0xc0, 0x2e, 0x07, 0xe0, 0x65, 0xa1, 0x2a, 0xf9, 0xf9, 0x55, 0x81, 0xe9, 0x49, 0xb0, 0x27,
	0x91, 0x27, 0xe2, 0xaa, 0x04, 0xf9, 0x4f, 0x26, 0x45, 0x5b, 0x8f, 0x41, 0xac, 0x22, 0x89, 0xf2,
	0x16, 0x87, 0x5a, 0xc5, 0x86, 0xc4, 0x4c, 0xcd, 0x7c, 0xae, 0xec, 0x54, 0x57, 0x98, 0xf7, 0x18,
	0xbd, 0xd4, 0x78, 0xee, 0xa7, 0x30, 0x5a, 0x47, 0x13, 0xfb, 0x6d, 0x7e, 0x6b, 0x57, 0xf1, 0xc1,
	0xef, 0x6a, 0x67, 0xd2, 0x76, 0xd8, 0xf7, 0x2b, 0xb8, 0x6c, 0x4e, 0x5a, 0x91, 0xf7, 0xa0, 0xbb,
	0x2c, 0x33, 0xe1, 0xee, 0xf0, 0x6b, 0x1f, 0x2a, 0x4d, 0x1b, 0xe4, 0x39, 0xf4, 0xd7, 0x7f, 0x22,
	0x61, 0xfa, 0xf8, 0xbf, 0x59, 0x32, 0x35, 0x8b, 0x8c, 0xff, 0xaf, 0x6d, 0xc7, 0x2d, 0x96, 0x1d,
	0xa3, 0xe8, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x89, 0x59, 0xc5, 0x33, 0x0e, 0x00, 0x00,
}
